### ISSUE TITLE
Getting IllegalStateException when loading jar as javaagent

### ISSUE THREAD

**Issue by davidnarayan** [prometheus/jmx_exporter#116]
I'm attempting to use the JMX exporter as a javaagent to monitor Kafka. I'm getting this error on startup:

```
2017-02-20 08:55:26.235:WARN:ipjsoejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:5127: java.lang.IllegalStateException: !accepting
java.lang.IllegalStateException: !accepting
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:333)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.Server.doStart(Server.java:288)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
FATAL ERROR in native method: processing of -javaagent failed
```

I've tried a number of different settings to no avail. Any pointers would be much appreciated!

I'm running the following software versions:

Linux: CentOS 7 (3.10.0-327.4.4.el7.x86_64)
Java: 1.7.0_75-b13
Kafka: 0.9.0

The jar was built using the same Linux and Java versions.

**Comment by brian-brazil** [comment]
I'm not sure what's going on here. Is something else listening on the port already?

**Comment by davidnarayan** [comment]
I agree -- it's a head scratcher for sure. 

Nothing else is listening on the port. I've tried several combinations of the startup parameters:

1. `5127`
2. `127.0.0.1:5127`
3. `0.0.0.0:5127`
4. Different ports as well...

All of them result in the same issue. 

I'm guessing that it's environmental but I was hoping that maybe someone else has seen this issue.

**Comment by brian-brazil** [comment]
Have you tried an strace to see what's going on at the syscall level?

**Comment by davidnarayan** [comment]
That's a good suggestion. I tried that but it wasn't clear to me what was causing the failure. I've attached the trace and the log.

[kafkaServer.txt](https://github.com/prometheus/jmx_exporter/files/790144/kafkaServer.txt)
[strace.txt](https://github.com/prometheus/jmx_exporter/files/790146/strace.txt)

**Comment by davidnarayan** [comment]
So, I was finally able narrow down the issue. We are attempting to use this jar to monitor Apache Kafka. The issue occurs when using the version of Kafka that is built for Scala 2.10. It does _not_ occur when using the version of Kafka that is built for Scala 2.11.

**Comment by brian-brazil** [comment]
That's odd, the code should be completely isolated from anything like that and only talking over JMX  to the rest of the JVM.

**Comment by davidnarayan** [comment]
The latest version of the JMX exporter (compiled from master) does not exhibit this issue.

**Comment by bencoughlan** [comment]
The latest version? You mean version 1.0 of the prometheus jmx exporter?
