### ISSUE TITLE
Error: Mapping Values Are Not Allowed Here

### ISSUE THREAD

**Issue by rjafarkhani** [prometheus/jmx_exporter#142]
When running this with Kafka, I'm receiving a the following error. Not sure if an actual issue, but I'm at the end of my rope:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: mapping values are not allowed here
 in 'reader', line 290, column 22:
    <!-- blob contrib key: blob_contributors:v21:e1ff8c2a ...
                         ^

        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.load(Yaml.java:393)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:72)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:39)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by brian-brazil** [comment]
This looks like you're loading the wrong file as a config file to me.

**Comment by rjafarkhani** [comment]
Touche! What's funny is that a) I had a gut feeling this was something so simple as this, b) I had already reviewed the config but having spent so many hours troubleshooting, it didn't click that it was an html page I wgetted by mistake! Must be losing mind... thanks for sharing some of your sanity!

**Comment by sibendu** [comment]
Oh; I have done the same, and wasted an hr of life. Thanks for saving me from wasting more. Amen.
