### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by liangxm** [prometheus/jmx_exporter#150]
when  I run my jar with /usr/local/jdk1.7.0_55/bin/java -javaagent:/alidata/projects/config/jmx_prometheus_javaagent-0.9.jar=1235:/alidata/projects/config/config1.yaml -jar /alidata/projects/jsb_v2/tasks/xx.jar,
this issue happened!

SEVERE: JMX scrape failed: java.lang.NullPointerException
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.processBeanValue(JmxScraper.java:254)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:157)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:119)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:401)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:143)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:158)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:128)
	at java.util.Collections.list(Collections.java:3688)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:40)
	at io.prometheus.jmx.shaded.javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at io.prometheus.jmx.shaded.javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.Server.handle(Server.java:365)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

**Comment by brian-brazil** [comment]
This is likely a race due to a field being removed from CompositeData.

**Comment by linqianqiu** [comment]
Is this the JDK version of the problem?

**Comment by brian-brazil** [comment]
I don't understand your question.

**Comment by linqianqiu** [comment]
I found the problem!
because Druid which initiated the init method.

[problem]
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">

[no problem]
<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource" destroy-method="close">

ps:
The root cause is what I have not found yet, But for this reason, I decided to temporarily give up using Druid.

**Comment by brian-brazil** [comment]
Unfortunately there's a fair few buggy jmx implementations out there. We shouldn't fail the whole scrape though then this happens, if you have an easy to reproduce way to make this happen we can add some try/catches to handle it more gracefully.

**Comment by VinkDong** [comment]
@r1cksun I have the same problem, how do you solve it 
```
Nov 01, 2017 10:43:17 AM io.prometheus.jmx.JmxScraper logScrape
          : scrape: 'com.alibaba.druid{type=DruidDataSourceStat}DataSourceList': tabulardata
Nov 01, 2017 10:43:17 AM io.prometheus.jmx.JmxCollector collect
          : JMX scrape failed: java.lang.NullPointerException
	at io.prometheus.jmx.JmxScraper.processBeanValue(JmxScraper.java:256)
	at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:159)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:120)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:415)
```
