### ISSUE TITLE
Getting errors JMX scrape failed: Failed to retrieve RMIServer stub

### ISSUE THREAD

**Issue by zemiak** [prometheus/jmx_exporter#171]
Hello,

since I deployed jmx_exporter into our production setup, I'm getting those error on every JMX scrape. It's quite annoying, as the logs are full of these exceptions and it's quite hard to search for anything "normal" in the logs now :-)

Any suggestion is welcome
Thanks,
Miroslav

Edit: surprisingly, the scraping works and we have the numbers in Prometheus/Grafana

Our setup: a Payara (Glassfish) application running inside of a docker container

Docker port mapping:
`-p 9204:8089`

Agent JVM parameter:
`-javaagent/opt/java-agents/jmx_prometheus_javaagent-0.9.jar=8089\\:/opt/java-agents/jmx_exporter.yaml`

YAML config:
```
---
username: 
password: 

rules:
  - pattern: ".*"
```

Exception:
`[#|2017-08-07T14:40:22.560+0000|SEVERE|Payara 4.1|io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector|_ThreadID=10;_ThreadName=jmx_exporter-10;_TimeMillis=1502116822560;_LevelValue=1000;|JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:106)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:401)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:143)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:158)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:128)
        at java.util.Collections.list(Collections.java:5240)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:40)
        at io.prometheus.jmx.shaded.javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
        at io.prometheus.jmx.shaded.javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.Server.handle(Server.java:365)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:122)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1957)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1924)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 30 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:118)
        ... 36 more`

**Comment by brian-brazil** [comment]
This is most likely that your application has broken JMX somehow.

**Comment by zemiak** [comment]
can be, can you point me to some direction?

**Comment by brian-brazil** [comment]
I'd suggest starting with the stack trace.

**Comment by pauldorman** [comment]
I see the same issue with Tomcat 7. There are no errors connecting locally with jmxterm or remotely with JVisualVM. I have tried both the downloadable JAR from the documentation and one I built myself.

**Comment by MarvAmBass** [comment]
Hi @zemiak,

I just run into the same problem with payara.

I'm not using the agent but the httpserver.

It was solved after I did the following in the configuration of jmx_exporter:

* enabled ssl
* added the trust store
* added admin username/password for payara

maybe this can help you

**Comment by benjaminguttmann-avtq** [comment]
The configuration @MarvAmBass mentioned solved the problem for me as well (using the httpserver as well).

**Comment by YuvalItzchakov** [comment]
For future reference, I had a similar problem where the stub would fail to load with the same error (JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub). It turns out I had the `localhost` property set in the `prometheus.conf` file, but was setting it to a different port number when starting the `HTTPServer`. I removed the property and set it explicitly via the constructor, and it worked.

**Comment by zemiak** [comment]
I am truly sorry for leaving this open for so long. I really do not remember, what was the solution, but most probably adding

`ssl: false`

into the config file.

**Comment by jkilgrow** [comment]
> I'd suggest starting with the stack trace.

how is that a helpful direction?

**Comment by ardenxu** [comment]
we got similar error when using jmx with application,  anyone can give some light on this? 

1. config file:

`sh-4.2$ cat /usr/src/config.yaml 
startDelaySeconds: 0
hostPort: 127.0.0.0:7676
username: 
password: 
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
  - pattern: ".*"
`

2. start command opts:

`-Xms4096m -Xmx4096m -javaagent:/usr/src/jmx_javaagent-0.12.0.jar=7676:/usr/src/config.yaml -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/CSSBackGroundTask/logs/common -Dfile.encoding=UTF-8 -Dlogging.config=/usr/local/hitv/css-back-ground-task-logback.xml -Dspring.config.location=/usr/local/hitv/application.yml`

`2019-07-30 09:31:34,737 ERROR [pool-1-thread-4] [i.p.j.s.i.p.j.JmxCollector:473] - JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: Exception creating connection
 to: 127.0.0.0; nested exception is:
        java.net.SocketException: Network is unreachable (connect failed)]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:94)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:468)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:59)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: Exception creating connection to: 127.0.0.0; nested exception is:
        java.net.SocketException: Network is unreachable (connect failed)]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 17 more
Caused by: java.rmi.ConnectIOException: Exception creating connection to: 127.0.0.0; nested exception is:
        java.net.SocketException: Network is unreachable (connect failed)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:631)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 22 more
Caused by: java.net.SocketException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
        at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
        ... 27 more
`

**Comment by brothelul** [comment]
I reproduced this question just now, and solved it by expose the jmx port of target application like below.`-Dcom.sun.management.jmxremote.port=1234

-Dcom.sun.management.jmxremote.ssl=false

 -Dcom.sun.management.jmxremote.authenticate=false `

**Comment by Sunyelw** [comment]
check your config.yaml if this port belongs server not client.
