### ISSUE TITLE
Error JMS Queue - Wildfly

### ISSUE THREAD

**Issue by acolatto** [prometheus/jmx_exporter#187]
When I enable JMX Prometheus Exporter version 0.10, the following error occurs every time I access /metrics in the Wildfly 9.0.2 Final server.log, but, the application works correctly and /metrics exports the information normally (with a timeout of 2 minutes, but exports).

I inform that, I have the exporter in other applications and no other one has presented this error. The settings of the jmx prometheus exporter are identical.

`08:36:23,020 ERROR [org.jboss.as.controller.management-operation] (pool-1-thread-3) WFLYCTL0013: Operation ("read-attribute") failed - address: ([
    ("subsystem" => "messaging"),
    ("hornetq-server" => "default"),
    ("runtime-queue" => "jms.queue.AlteracaoProcessoTrabalhoCRMQueue")
]): java.lang.IllegalArgumentException: newValue is null
	at org.jboss.dmr.ModelNode.set(ModelNode.java:499)
	at org.jboss.as.messaging.QueueReadAttributeHandler.executeRuntimeStep(QueueReadAttributeHandler.java:138)
	at org.jboss.as.controller.AbstractRuntimeOnlyHandler$1.execute(AbstractRuntimeOnlyHandler.java:53)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:803)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:601)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:354)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:330)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1183)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:362)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:205)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.execute(ModelControllerMBeanHelper.java:474)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:251)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:212)
	at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:129)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:400)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:152)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:120)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:415)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:180)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:213)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:134)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:43)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Apparently there is some flaw in the hornet and I do not know what it is.

Can someone help me?

**Comment by acolatto** [comment]
In numerous surveys and tests, the development team discovered that the application with error had the configuration file of the "hornetq-jmx.xml" queues and jmx_prometheus_exporter did not find the configuration.

They set the artemisq and pointed the queues at him.

Summary: The configuration of the queues was externalized and the hornetq-jmx.xml was removed.

Problem solved.
