### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by tj13** [prometheus/jmx_exporter#190]
JMX_exporter caused the JVM process high cpu usage  and prometheus server failed to query any JMX metrics.

after investigating via commands ps and jstack, it looks like due to a lock contention

output of ps:

ps -Leo pid,lwp,user,comm,pcpu --no-headers | sort -rnk 5
     1     31 root     java            27.2
     1     59 root     java             1.1
     1     25 root     java             0.2

output of jstack:

"jmx_exporter-8 Selector0" #8 daemon prio=5 os_prio=0 tid=0x00007f463470d800 **_nid=0x1f_** runnable [0x00007f46200a4000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Object.hashCode(Native Method)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint.toString(SelectChannelEndPoint.java:766)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at **_io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint.dispatch(SelectChannelEndPoint.java:224)
	- eliminated <0x00000000c226f428> (a io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint.schedule(SelectChannelEndPoint.java:191)
	- locked <0x00000000c226f428> (a io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectChannelEndPoint)
	at_** io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:619)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.io.nio.SelectorManager$1.run(SelectorManager.java:290)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at io.prometheus.jmx.shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

The stack of busy(1.1%) thread(59/0x3b) of java process(1) of user(root):
"Old I/O datagram worker ([id: 0x513f0cd7, 0.0.0.0/0.0.0.0:5140])" #39 prio=5 os_prio=0 tid=0x00007f45ac0d9000 nid=0x3b runnable [0x00007f461a468000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	- locked <0x00000000c1a87340> (a java.net.PlainDatagramSocketImpl)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	- locked <0x00000000c1a87340> (a java.net.PlainDatagramSocketImpl)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	- locked <0x00000000eb302898> (a java.net.DatagramPacket)
	- locked <0x00000000c1a872f0> (a java.net.MulticastSocket)
	at org.jboss.netty.channel.socket.oio.OioDatagramWorker.run(OioDatagramWorker.java:72)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by brian-brazil** [comment]
Please try a newer version of the jmx exporter.

**Comment by tj13** [comment]
already the latest version~  and the JDK version is 1.8.0_144

**Comment by brian-brazil** [comment]
That's not the latest version, as it's still using jetty.

**Comment by tj13** [comment]
@brian-brazil thanks for your mention, already update to version 0.10.
i'll follow up it~

**Comment by tj13** [comment]
issue reproduced again, prometheus server failed to query JMX metrics, it's empty output.  the cpu usage is normal~

output of jstack as below:


"Old I/O datagram worker ([id: 0x350a5d08, 0.0.0.0/0.0.0.0:5140])" #33 prio=5 os_prio=0 tid=0x00007f67440ca000 nid=0x35 runnable [0x00007f6790e00000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	- locked <0x00000000c1a7ab10> (a java.net.PlainDatagramSocketImpl)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	- locked <0x00000000c1a7ab10> (a java.net.PlainDatagramSocketImpl)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	- locked <0x00000000eb5f5100> (a java.net.DatagramPacket)
	- locked <0x00000000c1a7aac0> (a java.net.MulticastSocket)
	at org.jboss.netty.channel.socket.oio.OioDatagramWorker.run(OioDatagramWorker.java:72)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"RMI TCP Connection(368)-172.0.1.75" #96 daemon prio=5 os_prio=0 tid=0x00007f6758009000 nid=0x73 runnable [0x00007f6723fbc000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000000c26d50c0> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:550)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$7/1549170569.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

The stack of busy(0.1%) thread(25/0x19) of java process(1) of user(root):
"VM Thread" os_prio=0 tid=0x00007f67b016e000 nid=0x19 runnable 

"RMI TCP Connection(369)-172.0.1.75" #97 daemon prio=5 os_prio=0 tid=0x00007f6758009800 nid=0x74 runnable [0x00007f6723f3a000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000000c26d2ab0> (a java.io.BufferedInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:550)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$7/1549170569.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"RMI Scheduler(0)" #62 daemon prio=5 os_prio=0 tid=0x00007f6784029800 nid=0x51 waiting on condition [0x00007f6723ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c1910c58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"630826439@qtp-1156799458-13" #60 prio=5 os_prio=0 tid=0x00007f671c02e000 nid=0x4f in Object.wait() [0x00007f6723d71000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:626)
	- locked <0x00000000c1c99830> (a org.mortbay.thread.QueuedThreadPool$PoolThread)

"pool-1-thread-5" #48 prio=5 os_prio=0 tid=0x00007f676400b000 nid=0x43 runnable [0x00007f6790472000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	- locked <0x00000000c1d51bf0> (a java.lang.Object)
	at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
	- locked <0x00000000c2330418> (a sun.net.httpserver.Request$WriteStream)
	at sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:78)
	at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:444)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	- locked <0x00000000c232bb18> (a java.io.ByteArrayOutputStream)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:55)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-4" #47 prio=5 os_prio=0 tid=0x00007f6764009000 nid=0x42 runnable [0x00007f67904b3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	- locked <0x00000000c1d52358> (a java.lang.Object)
	at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
	- locked <0x00000000c1eaab50> (a sun.net.httpserver.Request$WriteStream)
	at sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:78)
	at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:444)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	- locked <0x00000000c1eaab98> (a java.io.ByteArrayOutputStream)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:55)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-3" #46 prio=5 os_prio=0 tid=0x00007f6764007800 nid=0x41 runnable [0x00007f67904f4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	- locked <0x00000000c1d51e68> (a java.lang.Object)
	at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
	- locked <0x00000000c236ad00> (a sun.net.httpserver.Request$WriteStream)
	at sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:78)
	at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:444)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	- locked <0x00000000c2366400> (a java.io.ByteArrayOutputStream)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:55)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-1-thread-2" #45 prio=5 os_prio=0 tid=0x00007f6764005800 nid=0x40 runnable [0x00007f6790535000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	- locked <0x00000000c1d52b28> (a java.lang.Object)
	at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
	- locked <0x00000000c1ef2b28> (a sun.net.httpserver.Request$WriteStream)
	at sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:78)
	at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:444)
	at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
	- locked <0x00000000c2370f50> (a java.io.ByteArrayOutputStream)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:55)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by brian-brazil** [comment]
What exactly should I be looking at there?

My default assumption is a bug in the jmx provider.

**Comment by brian-brazil** [comment]
Closing due to staleness.
