### ISSUE TITLE
ClassCastException on invalid config

### ISSUE THREAD

**Issue by wsargent** [prometheus/jmx_exporter#230]
Using JMX prometheus javaagent 0.10:

```
---
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
- pattern: kafka.(.+)<type=(.+), client-id=(.+)>
  labels:
    - client-id: $3

- pattern: kafka.(.+)<type=(.+), topic=(.+), client-id=(.+)>
  labels:
    - topic: $3
    - client-id: $4

# - pattern: 'kafka.producer<type=producer-metrics, client-id=simple-service-client1><>buffer-exhausted-rate:'
```

yields the following stack trace:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:196)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:36)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by wsargent** [comment]
This isn’t about what the invalid config, but about the fact that it produces a class cast exception instead of an error message indicating invalid config
