### ISSUE TITLE
Bad config files or "used" socket crashes whole JVM (producing crash dumps)

### ISSUE THREAD

**Issue by msperl** [prometheus/jmx_exporter#242]
Using 0.2.0 when I use javaagent with a port already taken I get:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:433)
at sun.nio.ch.Net.bind(Net.java:425)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)
at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)
at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)
... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```
And then the JVM crashes.

Simmilarly a bad config also crashes the JVM - I do not have the exceptions at hand any longer.

Maybe better error/exception handling so that the agent stops gracefully?

**Comment by msperl** [comment]
Not to terminate the JVM, but write out a warning and stop the agent, but leaving the JVM and the main process running.

**Comment by brian-brazil** [comment]
The agent is loaded before anything else, and I don't think it's wise to be running a server that you can't monitor. Terminating is the thing to do when you can't start up properly.

**Comment by msperl** [comment]
But triggering a crashdump that is handled by systemd-crashdump consuming lots of cpu (and disk space) - especially when automatic restart is enabled is even worse.

I see up to 10 systemd-crashdumps running concurrently just because of a typo!

In the worsted case the http port of the agent is closed and that will get detected by the monitoring, so that corrective steps can be taken without bringing the system to its kees...

**Comment by brian-brazil** [comment]
That sounds like a problem with systemd, any other configuration issue would have the same outcome.

**Comment by gavinmcnair** [comment]
I had this issue as well. Simple port conflict causes the whole JVM to crash.

It would be good if this can be handled nicely (i.e. appropriate error and clean exit)

**Comment by brian-brazil** [comment]
It is returning a java stack trace, and the cause is obvious from the stacktrace.

**Comment by jlvale** [comment]
Someone managed to find what ports were conflicting?

**Comment by tkhkokd** [comment]
> Someone managed to find what ports were conflicting?

No...still happening
