### ISSUE TITLE
jmx_prometheus_httpserver is unable to connect to a remote Wildfly on port 9990 - Unsupported protocol: http-remoting-jmx

### ISSUE THREAD

**Issue by juliohm1978** [prometheus/jmx_exporter#249]
I'm trying to collect metrics from a remote Wildfly 8.2.1, and for this particular instance I cannot configure the agent locally at that server. Management port 9990, however, is available.

Running jmx_prometheus_httpserver with the following configuration:

```
java -cp jboss-client.jar -jar jmx_prometheus_httpserver-0.2.1-SNAPSHOT-jar-with-dependencies.jar 127.0.0.1:28686 jmx_exporter.yaml
```

This is what `jmx_exporter.yaml` looks like:

```
startDelaySeconds: 0
jmxUrl: service:jmx:http-remoting-jmx://<remote_wildfly_host>:9990
username: myuser
password: mypassword
ssl: false
```

The server starts well, but as soon as I try to scrape metrics, the following error comes up.

```
Feb 26, 2018 4:45:32 PM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.net.MalformedURLException: Unsupported protocol: http-remoting-jmx
	at javax.management.remote.JMXConnectorFactory.newJMXConnector(JMXConnectorFactory.java:359)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:269)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:94)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:456)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:180)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:144)
	at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:131)
	at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:60)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Please note that `jboss-client.jar` is in the classpath.

Curiously, if I try to use JmxScraper by itself from the collector package, that seems to work.

```
java -cp collector-0.2.1-SNAPSHOT.jar:jboss-client.jar io.prometheus.jmx.JmxScraper service:jmx:http-remoting-jmx://<remote_wildfly_host>:9990 myuser mypassword
```

Any ideas of why jmx_prometheus_httpserver is apparently not loading jboss-client.jar?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by SakaSun** [comment]
I managed to run the example above by changing the pom file of the collector and rebuilding it.
```
--- a/collector/pom.xml
+++ b/collector/pom.xml
@@ -31,6 +31,21 @@
       <artifactId>snakeyaml</artifactId>
       <version>1.16</version>
     </dependency>
+    <dependency>
+      <groupId>org.jboss.remotingjmx</groupId>
+      <artifactId>remoting-jmx</artifactId>
+      <version>2.0.0.Final</version>
+      <exclusions>
+        <exclusion>
+          <groupId>org.jboss.logging</groupId>
+          <artifactId>jboss-logging-processor</artifactId>
+        </exclusion>
+        <exclusion>
+          <groupId>org.jboss.logmanager</groupId>
+          <artifactId>jboss-logmanager</artifactId>
+        </exclusion>
+      </exclusions>
+    </dependency>
   </dependencies>
```

**Comment by juliohm1978** [comment]
For anyone else stumbling into this, PR #254 provides a patch that creates an additional jmx_prometheus_httpserver bundle compatible with willdfly (`jmx_prometheus_httpserver-*-jar-with-dependencies-wildfly.jar`).

PR was rejected, but the patch might help anyone in the future.

**Comment by bdellegrazie** [comment]
I know this is closed but the root cause of the collector not working with the jboss-client.jar was simply that "-jar" ignores any other classpath modification instructions on the command line - so the "-cp jboss-client.jar" was ignored by Java as per the documentation.

It works perfectly if you use:
java -cp jmx_prometheus_httpserver-0.3.1-jar-with-dependencies.jar:jboss-client.jar io.prometheus.jmx.WebServer <normal command line settings>
