### ISSUE TITLE
Process crash with embedded javaangent and -XX:+UseConcMarkSweepGC

### ISSUE THREAD

**Issue by daicoden** [prometheus/jmx_exporter#251]
If you enable concurrent mark sweep via `-XX:+UseConcMarkSweepGC`, the jvm throws an exception on bootup with the following.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.InternalError: Memory Pool not found
        at sun.management.MemoryPoolImpl.getUsage0(Native Method)
        at sun.management.MemoryPoolImpl.getUsage(MemoryPoolImpl.java:96)
        at io.prometheus.jmx.shaded.io.prometheus.client.hotspot.MemoryPoolsExports.addMemoryPoolMetrics(MemoryPoolsExports.java:106)
        at io.prometheus.jmx.shaded.io.prometheus.client.hotspot.MemoryPoolsExports.collect(MemoryPoolsExports.java:125)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:100)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
        at io.prometheus.jmx.shaded.io.prometheus.client.Collector.register(Collector.java:139)
        at io.prometheus.jmx.shaded.io.prometheus.client.Collector.register(Collector.java:132)
        at io.prometheus.jmx.shaded.io.prometheus.client.hotspot.DefaultExports.initialize(DefaultExports.java:24)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:48)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by brian-brazil** [comment]
Which version is this with?

**Comment by daicoden** [comment]
master

**Comment by roidelapluie** [comment]
Which JVM is this? I can not reproduce the bug.

**Comment by roidelapluie** [comment]
Tested with Java 8 and 9 without success

**Comment by marcust** [comment]
@daicoden can you give more information? Especially `java -version` would be helpful as well as the exact command line you are running. Can you reproduce that with `run_sample_server.sh` from here?

**Comment by marcust** [comment]
I'm mostly wondering if you managed to hit https://bugs.openjdk.java.net/browse/JDK-8025089

**Comment by daicoden** [comment]
Ah sorry, I lost track of this.

```
java -Dfile.encoding=UTF-8 \
  -server \
  -Xms512m -Xmx1g -Xmn512m \
  -XX:SurvivorRatio=6 \
  -XX:+CMSParallelRemarkEnabled \
  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 \
  -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark \
  -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -Xloggc:"/var/log/cfhtapi/cfhtapi-gc.log" \
  -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M \
  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/var/log/cfhtapi/cfhtapi-`date`.hprof" \
  -javaagent:./jmx_prometheus_javaagent-0.3.1-SNAPSHOT.jar=9404:./jmx_exporter.config.yml \
  -Duser.timezone=UTC \
  -jar cfhtapi-HEAD-SNAPSHOT.jar
```

```
-bash-4.2$ java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
-bash-4.2$
```

I'll close this and re-open if I run into it again next time I do GC tuning.
