### ISSUE TITLE
whitelist attributenames

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/jmx_exporter#257]
IT would be great to be able to whitelist attributenames -- not only objectnames

**Comment by brian-brazil** [comment]
Why do you want this? You can already limit the results via regex.

**Comment by roidelapluie** [comment]
To avoid:
```
2018-03-12 00:00:08,826 ERROR [org.jboss.as.controller.management-operation] (default task-58) JBAS014612: Operation ("read-attribute") failed - address: ([
    ("subsystem" => "messaging"),
    ("hornetq-server" => "default"),
    ("runtime-queue" => "jms.queue.declaration.sending.queue")
]): java.lang.IllegalArgumentException: newValue is null
        at org.jboss.dmr.ModelNode.set(ModelNode.java:499)
        at org.jboss.as.messaging.QueueReadAttributeHandler.executeRuntimeStep(QueueReadAttributeHandler.java:136)
        at org.jboss.as.controller.AbstractRuntimeOnlyHandler$1.execute(AbstractRuntimeOnlyHandler.java:89)
        at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:660)
        at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:501)
        at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:298)
        at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:293)
        at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:276)
        at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:150)
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.execute(ModelControllerMBeanHelper.java:473)
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:250)
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:211)
        at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:126)
        at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:393)
        at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:152) [collector-0.2.0.jar:]
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:120) [collector-0.2.0.jar:]
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:415) [collector-0.2.0.jar:]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183) [simpleclient-0.2.0.jar:]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216) [simpleclient-0.2.0.jar:]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137) [simpleclient-0.2.0.jar:]
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22) [simpleclient_common-0.2.0.jar:]
        at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:43) [simpleclient_servlet-0.2.0.jar:]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
```

**Comment by brian-brazil** [comment]
The JMX exporter should handle such exceptions gracefully, but fundamentally this is an issue in the jboss code that needs to be fixed.

**Comment by brian-brazil** [comment]
I believe jboss has fixed these.
