### ISSUE TITLE
StackOverflowError in JmxScraper

### ISSUE THREAD

**Issue by aukevanleeuwen** [prometheus/jmx_exporter#267]
Once in a while, while scraping I'm getting the following exception. I've only once been able to reproduce it reliably, however I was not able to debug which value triggered it. (Once I started debugging it never showed up again). 

I'm pretty sure this StackOverflow answer hits the nail on the head: https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings

> Unfortunately, Java's builtin regex support has problems with regexes containing repetitive alternative paths (that is, (A|B)*). This is compiled into a recursive call, which results in a StackOverflow error when used on a very large string.

This is the `Pattern`:

```java
Pattern.compile(
                "([^,=:\\*\\?]+)" + // Name - non-empty, anything but comma, equals, colon, star, or question mark
                        "=" +  // Equals
                        "(" + // Either
                        "\"" + // Quoted
                        "(?:" + // A possibly empty sequence of
                        "[^\\\\\"]" + // Anything but backslash or quote
                        "|\\\\\\\\" + // or an escaped backslash
                        "|\\\\n" + // or an escaped newline
                        "|\\\\\"" + // or an escaped quote
                        "|\\\\\\?" + // or an escaped question mark
                        "|\\\\\\*" + // or an escaped star
                        ")*" +
                        "\"" +
                        "|" + // Or
                        "[^,=:\"]*" + // Unquoted - can be empty, anything but comma, equals, colon, or quote
                        ")");
```

I don't understand the pattern completely, but the middle part is a likely suspect. 

I'll try to dig in a bit, but maybe you can give me a few words on what exactly we're trying to match here. Do you have some example Strings you're trying to match?

---
```
Exception in thread "pool-1-thread-2" java.lang.StackOverflowError
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)

	... some 1400 lines ....

	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4804)
	at java.util.regex.Pattern$Prolog.match(Pattern.java:4741)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4272)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Matcher.match(Matcher.java:1270)
	at java.util.regex.Matcher.lookingAt(Matcher.java:682)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.getKeyPropertyList(JmxScraper.java:178)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:161)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:120)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:415)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:180)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:213)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:134)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:43)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brian-brazil** [comment]
It's matching against JMX properties, so the question is what does look like in your application.

**Comment by aukevanleeuwen** [comment]
I realise that, but I don't seem to have a stable reproduction path as (apparently) MBeans come and go. But I'm not dealing with MBean property names of huge length either of course. I'm kind of surprised of how difficult the regex seems to be. 

I've tried to look through the JavaDoc of `ObjectName` and the string representation is indeed crappy to parse. However I don't understand how the parsed `LinkedHashMap` differs from a call to `mbeanName.getKeyPropertyList()`. This will return a `Hashtable`, which in the end is a `Map` as well. Do you explicitly need the iteration order of a `LinkedHashMap`?

**Comment by brian-brazil** [comment]
Yes, we need the ordering.

**Comment by aukevanleeuwen** [comment]
You need the order to be consistent, or exactly as the string would output them? If you just need them to be consistent, you can do something like this perhaps? Really trying to avoid the regex here. I have nothing against regular expressions (I even like them :-) ) but I don't like the StackOverflowErrors I'm getting at this moment. Presumably I'm not the only one either.

```java
Hashtable<String, String> properties = mbeanName.getKeyPropertyList();

ArrayList<String> keys = new ArrayList<>(properties.keySet());
keys.sort(String::compareToIgnoreCase);

keys.forEach(key -> {
  keyProperties.put(key, properties.get(key));
});
```

`keyProperties` being the original `LinkedHashMap<String, String>` you are currently using.

**Comment by brian-brazil** [comment]
Exactly as they would be output.

**Comment by aukevanleeuwen** [comment]
Okay, I've tried to digg into this a bit. I'm not entirely sure what value it's throwing these `StackOverflowError`s on, but I can see from fiddling with the regex on regex101.com that it can indeed be quite resource intensive. Compare for example:

https://regex101.com/r/fVSOlB/1 (324 steps, adding 12 steps for every escaped `*`) and
https://regex101.com/r/tp00tS/1 (134 steps, adding 6 steps for every escaped `*`)

Of course this is PCRE regex flavor, but java seems to behave similarly. I don't know the exact pattern that is causing this, but I'd like to suggest  to replace the pattern with the second one, which doesn't do (as much?) backtracking for the quoted value.

**Comment by aukevanleeuwen** [comment]
Any estimates on releasing a new version?

**Comment by brian-brazil** [comment]
I've put it on my todo list, but probably no sooner than next week.

**Comment by aukevanleeuwen** [comment]
Okay, thanks for the merge. Will have a look next week.

Btw, the version number change from `x.y` to `y.x.z` didn't work out well unfortunately. You effectively went back in time (versioning wise) from `0.10(.0)` to `0.1.0`. 

People that are searching for new artifacts via maven repositories for example will not see any newer versions 'by default' since the latest one shows as `0.10`. 

See for example here: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.prometheus.jmx%22%20a%3A%22jmx_prometheus_javaagent%22

Just wanted to let you know, in case you didn't realise this unwanted side-effect.

**Comment by aukevanleeuwen** [comment]
May I be so blunt to kindly ask for a release, so I can incorporate the fix in our base image any time soon?
