### ISSUE TITLE
io.prometheus.jmx.JmxCollector collect

### ISSUE THREAD

**Issue by ToldaCZ** [prometheus/jmx_exporter#272]
Hello,

if I start jmx_export prometheus http server(see below) and connect jmx to my java application I get an error when I try show http (port 5556):

SEVERE: JMX scrape failed: java.lang.ClassCastException: java.lang.Long cannot be cast to javax.management.Attribute
        at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:156)
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:456)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:147)
        at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:134)
        at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:60)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

command:
java -jar /path/jmx_prometheus_httpserver-0.3.2-SNAPSHOT-jar-with-dependencies.jar 5556 /path/config.yml

P.S
run_sample_httpserver.sh working fine

**Comment by ToldaCZ** [comment]
Hello,
last functional version without mentioned issue is: httpserver-0.2
BR
Miroslav

**Comment by brian-brazil** [comment]
Which application is this? It sounds like it's returning bad data.

**Comment by ToldaCZ** [comment]
corrected on application side
