### ISSUE TITLE
Collector already registered that provides name: jmx_scrape_duration_seconds

### ISSUE THREAD

**Issue by arnaudlemaignen** [prometheus/jmx_exporter#290]
Hi all

I have a container in which 2 java processes are running.
I wanted to monitor those 2 processes with 2 JMX agents.

JMX exporter agent 0.3.1 version

First JVM is launched with 
-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=5558:/opt/jmx_exporter/jmx_java_config.yml

Second JVM is launched with 
-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=5556:/opt/jmx_exporter/jmx_java_config.yml

the 1st agent is working

```
$ curl localhost:5558
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="ParNew",} 28.0
```

but not the 2nd one

```
FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: jmx_scrape_duration_seconds
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
	at io.prometheus.jmx.shaded.io.prometheus.client.Collector.register(Collector.java:139)
	at io.prometheus.jmx.shaded.io.prometheus.client.Collector.register(Collector.java:132)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:47)
```

Did I missed something or is it a bug?

Thanks
Arnaud

**Comment by brian-brazil** [comment]
You got your invocation wrong, that only happens if you load the javaagent twice into the same JVM.

**Comment by saiwebaditya** [comment]
I have the same issue did it  get resolved?

**Comment by saiwebaditya** [comment]
I have the same issue.  Collector already registered that provides name: jmx_scrape_duration_seconds
how do we resolve this?
