### ISSUE TITLE
NullPointerException starting on Wildfly 10.1

### ISSUE THREAD

**Issue by tkuther** [prometheus/jmx_exporter#299]
I'm trying out jmx-exporter and I'm unable to start any of our Wildfly domains with this.

```
22:21:29,497 INFO  [org.jboss.as.process.Server:fin-server01.status] (ProcessController-threads - 3) WFLYPC0018: Starting process 'Server:fin-server01'
[Server:fin-server01] Exception in thread "main" java.lang.reflect.InvocationTargetException
[Server:fin-server01]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Server:fin-server01]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Server:fin-server01]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Server:fin-server01]   at java.lang.reflect.Method.invoke(Method.java:498)
[Server:fin-server01]   at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
[Server:fin-server01]   at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
[Server:fin-server01] Caused by: java.lang.NullPointerException
[Server:fin-server01]   at java.util.TreeMap.putAll(TreeMap.java:313)
[Server:fin-server01]   at java.util.TreeMap.<init>(TreeMap.java:185)
[Server:fin-server01]   at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:196)
[Server:fin-server01]   at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
[Server:fin-server01]   at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:47)
[Server:fin-server01]   ... 6 more
[Server:fin-server01] FATAL ERROR in native method: processing of -javaagent failed
```

jmx-exporter version is 0.3.1
Wildfly version is 10.1.0
JDK is Oracle 1.8.0u144

I'm using the configuration from example_configs/wildfly-10.yaml + startDelaySeconds: 120

**Comment by tkuther** [comment]
Hmm, there must have been something wrong with the config, I just can't tell what.
First I dropped all rules, it worked.
Then I added them back one by one, and it still works.

So, I can't reproduce my own issue as it seems now.
