### ISSUE TITLE
i can't run jmx_exporter,please help

### ISSUE THREAD

**Issue by cloud-op** [prometheus/jmx_exporter#333]
command1 : java -javaagent:./jmx_prometheus_javaagent-0.3.1.jar=8080:config.yaml 
command2 : java -javaagent:./jmx_prometheus_javaagent-0.3.1.jar=8080:config.yaml -jar jmx_prometheus_javaagent-0.3.1.jar

the error messages is same like this:
------------------------------------------------------------------------------------------------------------------

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalArgumentException: At most one of hostPort and jmxUrl must be provided
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:120)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:47)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)
------------------------------------------------------------------------------------------------------

config.yaml is 
-----------------------------------------------------------------------
startDelaySeconds: 0
hostPort: 10.160.100.7:9999
username: 
password: 
jmxUrl: service:jmx:rmi:///jndi/rmi://10.160.100.7:9999/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
----------------------------------------------------------------------------

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
