### ISSUE TITLE
JMX exporter causing WARN messages in server.log file on wildfly 8.1.0 Final 

### ISSUE THREAD

**Issue by Vatsaldhar26** [prometheus/jmx_exporter#340]
I am running JMX exporter and letting it query my server which has wildfly 8.1.0 Final.
On the terminal, I am using the following command to run it :

java -jar jmx_prometheus_httpserver-0.3.2-SNAPSHOT-jar-with-dependencies.jar 9404 jmx_wildfly_config.yml

After I run the above command on the terminal and try to open localhost:9404, my server.log, on that server where wildfly 8.1.0 Final is present, gets populated with following WARN messages, coming in at like 100+ time within a span of 2 min. 

2018-11-29 05:50:20,654 WARN  [org.jboss.remotingjmx.protocol.v2.ServerCommon] (pool-2-thread-1) Unexpected internal error: java.lang.IllegalArgumentException
        at org.jboss.dmr.ModelValue.getChild(ModelValue.java:112) [jboss-dmr-1.2.0.Final.jar:1.2.0.Final]
        at org.jboss.dmr.ModelNode.get(ModelNode.java:856) [jboss-dmr-1.2.0.Final.jar:1.2.0.Final]
        at org.jboss.as.jmx.model.TypeConverters$ComplexTypeConverter.fromModelNode(TypeConverters.java:538) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.model.TypeConverters$ListTypeConverter.fromModelNode(TypeConverters.java:444) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.model.TypeConverters.fromModelNode(TypeConverters.java:114) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:245) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttributes(ModelControllerMBeanHelper.java:213) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttributes(ModelControllerMBeanServerPlugin.java:100) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttributes(PluggableMBeanServerImpl.java:410) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.remotingjmx.protocol.v2.ServerProxy$GetAttributesHandler.handle(ServerProxy.java:743)
        at org.jboss.remotingjmx.protocol.v2.ServerCommon$MessageReciever$1$1.run(ServerCommon.java:153)
        at org.jboss.as.jmx.ServerInterceptorFactory$Interceptor$1.run(ServerInterceptorFactory.java:75) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.ServerInterceptorFactory$Interceptor$1.run(ServerInterceptorFactory.java:70) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_131]
        at javax.security.auth.Subject.doAs(Unknown Source) [rt.jar:1.8.0_131]
        at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:94) [wildfly-controller-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.jmx.ServerInterceptorFactory$Interceptor.handleEvent(ServerInterceptorFactory.java:70) [wildfly-jmx-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.remotingjmx.protocol.v2.ServerCommon$MessageReciever$1.run(ServerCommon.java:149)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [rt.jar:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [rt.jar:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [rt.jar:1.8.0_131]

I am completely helpless, why these WARN messages are coming and I was hoping if I can get a hint for as in why this must be happening, or is there someplace where I am not doing something right.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
