### ISSUE TITLE
jmx_exporter example for kafka missing labels

### ISSUE THREAD

**Issue by chuck-ecob** [prometheus/jmx_exporter#355]
Found this error when trying to use the example:

https://github.com/prometheus/jmx_exporter/blob/6cd71b6c802b8c9f1f934fa00f832067d787b678/example_configs/kafka-2_0_0.yml#L31

https://github.com/prometheus/jmx_exporter/blob/6cd71b6c802b8c9f1f934fa00f832067d787b678/example_configs/kafka-2_0_0.yml#L85

Needs the following change:

```
$ git diff -w
diff --git a/kafka-b/files/kafka-2_0_0.yml b/kafka-b/files/kafka-2_0_0.yml
index 73129fd..0779920 100644
--- a/kafka-b/files/kafka-2_0_0.yml
+++ b/kafka-b/files/kafka-2_0_0.yml
@@ -29,7 +29,6 @@ rules:
     type: COUNTER
     labels:
       "$4": "$5"
-  type: COUNTER
   - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
     name: kafka_$1_$2_$3_total
     type: COUNTER
@@ -84,4 +83,5 @@ rules:
     name: kafka_$1_$2_$3
     type: GAUGE
     labels:
+      "$4": "$5"
     quantile: "0.$4"
```

**Comment by brian-brazil** [comment]
The duplicate is a harmless mistake, but the labels look right to me.

**Comment by chuck-ecob** [comment]
The lack of label causes kafka 2.1.0 to generate this error:

```
Feb 25 19:26:50 kafka-b1 systemd: Started Apache Kafka server (broker).
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: Exception in thread "main" java.lang.reflect.InvocationTargetException
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at java.lang.reflect.Method.invoke(Method.java:498)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: Caused by: java.lang.NullPointerException
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at java.util.TreeMap.putAll(TreeMap.java:313)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at java.util.TreeMap.<init>(TreeMap.java:185)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:196)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:52)
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: ... 6 more
Feb 25 19:26:51 kafka-b1 kafka-server-start.sh: FATAL ERROR in native method: processing of -javaagent failed
Feb 25 19:26:51 kafka-b1 systemd: kafka.service: main process exited, code=killed, status=6/ABRT
```

Removing the final stanza, or adding the label, would solve the problem.

**Comment by brian-brazil** [comment]
The file is fine, you have an indentation error though.

**Comment by chuck-ecob** [comment]
Please ignore the whitespace, I was trying to use yamllint to see if it was a parsing error (turns out it was not). But I assure you, adding this label on line 85 is what allows our kafka instances to now start up. Without it, it fails.

**Comment by brian-brazil** [comment]
That still doesn't seem right. Can you check for whitespace diffs?

**Comment by chuck-ecob** [comment]
I have to admit, I'm completely baffled. When bringing up a new cluster, I could not get a single member to start without adding this label. Now that the cluster is up and active, the example config is working. If you can help explain how that may be, I'm game.

Appreciate your questions, and you may close this issue.

**Comment by brian-brazil** [comment]
I'm guessing a bad version of the config got stuck somewhere.
