### ISSUE TITLE
JMX scrape failed: java.lang.NullPointerException mx.JmxScraper.scrapeBean(JmxScraper.java:156

### ISSUE THREAD

**Issue by AviNachman** [prometheus/jmx_exporter#362]
Hey 
i running with jmx_prometheus_javaagent-0.11.0.jar and getting on startup this exception below 
can u please advice?
i try also to debug and did not got any logs(https://www.robustperception.io/viewing-logs-for-the-jmx-exporter)

 io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.NullPointerException
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:156)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:460)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:59)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by brian-brazil** [comment]
The attributes look to be null, which shouldn't be possible. What are you using this with?

**Comment by AviNachman** [comment]
Hey Brian
i running on tomcat application and configure it with:
export JAVA_OPTS="${JAVA_OPTS} -javaagent:/scuser/nft/user/odonft01/jmx_prometheus_javaagent-0.11.0.jar=9099:/scuser/nft/user/odonft01/config.yml"

at config.yml i am using the example got from the site:
https://github.com/prometheus/jmx_exporter/blob/master/example_configs/tomcat.yml

**Comment by brian-brazil** [comment]
From the debug output, can you tell which mBean is causing this?

**Comment by AviNachman** [comment]
Thanks Brian, i configure the debug output as shown here:
 https://www.robustperception.io/viewing-logs-for-the-jmx-exporter 
but did not got any out... only on catalina.out can you direct me i configure it like that:
export JAVA_OPTS="${JAVA_OPTS} -Djava.util.logging.config.file=/scuser/nft/user/odonft01/logging.properties 
and create logging.properties with the values  on home directory (/scuser/nft/user/odonft01/)

**Comment by brian-brazil** [comment]
That's odd, you'd have to debug it yourself. You could also insert some print statements above the line that has the exception to figure out what's going on.

**Comment by AviNachman** [comment]
Thanks Brian,
I debugged the code and found that a class in my application code returns null value of attributeInfo when getMBeanInfo is called.

it fails on **JmxScraper** line 156: 
_for (Attribute attribute : attributes.asList()) {_

so i added before it a null check:
        _if(attributes == null){
            return;
        }_

then issue resolved.
could u please tell me if i could change code in jmx_exporter and how i am doing it in order to solve the issue.
or you can assist with it?

**Comment by brian-brazil** [comment]
We should be resilient to this, but that's also a bug in your application that should be fixed.

**Comment by AviNachman** [comment]
Thanks i will check it but can u also give support for that?

**Comment by brian-brazil** [comment]
If you want to put that in a PR and add a log line, that'd be great.

**Comment by AviNachman** [comment]
Hey Brian below is the pull request: 
https://github.com/prometheus/jmx_exporter/pull/363
