### ISSUE TITLE
Failed to get requested attribute

### ISSUE THREAD

**Issue by ChasevanHekken** [prometheus/jmx_exporter#373]
I added the JMX exporter and am getting the following errors:

It says failed to get requested attribute for a number of metrics.

threadPoolSize
statementDestroyerNumActiveThreads
statementCacheNumStatementsDefaultUser
numIdleConnections
statementDestroyerNumDeferredDestroyStatementsDefaultUser
upTimeMillisDefaultUser
statementDestroyerNumIdleThreads
statementDestroyerNumDeferredDestroyStatementsAllUsers
numFailedCheckinsDefaultUser
etc....

`Caused by: java.sql.SQLException: com.mchange.v2.c3p0.PoolBackedDataSource@9f36a249 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@f0a74fac [ acquireIncrement -> 1, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 2xxawwa11ttr753pjoklx|60a5d9f1, idleConnectionTestPeriod -> 100, initialPoolSize -> 0, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 30, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 30, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 0, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@a6b636b6 [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> 2xxawwa11ttr753pjoklx|21505e71, jdbcUrl -> jdbc:postgresql://prcroe00.cjvfzcpnts8z.us-east-1.rds.amazonaws.com:5432/prcroe00?ssl=true&reWriteBatchedInserts=true, properties -> {user=******, password=******} ], preferredTestQuery -> null, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> 2xxawwa11ttr753pjoklx|7152181d, numHelperThreads -> 3 ] has been closed() -- you can no longer use it.
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.assertCpds(AbstractPoolBackedDataSource.java:507)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:519)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getNumFailedIdleTestsDefaultUser(AbstractPoolBackedDataSource.java:212)
	... 23 more
2019-04-05 11:28:39,635 pool-1-thread-1 WARN [v2.c3p0.management.DynamicPooledDataSourceManagerMBean] Failed to get requested attribute: threadPoolSize
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor757.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.getAttribute(DynamicPooledDataSourceManagerMBean.java:366)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:152)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:120)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:415)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:180)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:213)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:134)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:59)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by brian-brazil** [comment]
That exception is coming from your application, so you should debug there.

**Comment by ChasevanHekken** [comment]
But there was no exception before adding the JMX exporter via the javaagent?

**Comment by brian-brazil** [comment]
Presumably nothing else was ever hitting the buggy mBean before.

**Comment by ChasevanHekken** [comment]
What is the correct syntax to blacklist this bean? v2.c3p0.management.DynamicPooledDataSourceManagerMBean

blacklistObjectNames: ["v2.c3p0.management.DynamicPooledDataSourceManagerMBean:*"]

**Comment by Rohlik** [comment]
I have similar problem...
My setting is:
```
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:10002/jmxrmi
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: ".*"
```
and I want get for example this bean:
`objectName="com.jolbox.bonecp:type=BoneCP" attribute="CacheHits"`
but there is no metric with this name in output.

There are many beans which I want collect but there are not exist in exporter output.

**Comment by brian-brazil** [comment]
This is an application issue, nothing for us to do here.
