### ISSUE TITLE
java.io.IOException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by Ramos82** [prometheus/jmx_exporter#431]
We use jmx_prometheus_javaagent-0.12.0.jar in combination with Apache Tomcat 8.5.x and OpenJDK 1.8.0_222-b10 on Windows Server 2016.
In the past few days we see the following error "java.io.IOException: An established connection was aborted by the software in your host machine" appearing and also in the Grafan dashboard data is missing. We see gaps in the graphs ranging from 2 to some as long as 10 minutes.

jmx_prometheus_javaagent is configured as follows under Tomcat properties:
-javaagent:D:\Program Files\prometheus\jmx_prometheus_javaagent-0.12.0.jar=9191:D:\Program Files\prometheus\config.yml

Below the exact error:

Transaction type: Web
Transaction name: /metrics
Error: java.io.IOException: An established connection was aborted by the software in your host machine

exception:
java.io.IOException: An established connection was aborted by the software in your host machine
at sun.nio.ch.SocketDispatcher.write0(Native Method)
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
at sun.nio.ch.IOUtil.write(IOUtil.java:65)
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
at sun.net.httpserver.ChunkedOutputStream.writeChunk(ChunkedOutputStream.java:125)
at sun.net.httpserver.ChunkedOutputStream.write(ChunkedOutputStream.java:87)
at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:444)
at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:168)
at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:238)
at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:73)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Can someone please explain why this is happening and where to look?

thank you.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
