### ISSUE TITLE
Not Able to scrape weblogic exposed MBeans using jmx_exporter

### ISSUE THREAD

**Issue by abhishekgupte999** [prometheus/jmx_exporter#438]
Hi,

**Comment by abhishekgupte999** [comment]
Hi,
I am trying to scrap weblogic exposed MBean, but i am getting below error always.
However, I am able to scrape weblogic exposed Mbeans using JConsole.

here is the error i am getting while scrapping.
org.omg.CORBA.NO_PERMISSION:   vmcid: 0x0  minor code: 0  completed: No
       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at java.lang.Class.newInstance(Class.java:442)
       at com.sun.corba.se.impl.protocol.giopmsgheaders.MessageBase.getSystemException(MessageBase.java:916)
       at com.sun.corba.se.impl.protocol.giopmsgheaders.ReplyMessage_1_2.getSystemException(ReplyMessage_1_2.java:116)
       at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.getSystemExceptionReply(CorbaMessageMediatorImpl.java:590)
       at com.sun.corba.se.impl.protocol.CorbaClientRequestDispatcherImpl.processResponse(CorbaClientRequestDispatcherImpl.java:489)
       at com.sun.corba.se.impl.protocol.CorbaClientRequestDispatcherImpl.marshalingComplete(CorbaClientRequestDispatcherImpl.java:373)
       at com.sun.corba.se.impl.protocol.CorbaClientDelegateImpl.invoke(CorbaClientDelegateImpl.java:148)
       at org.omg.CORBA.portable.ObjectImpl._invoke(ObjectImpl.java:475)
       at org.omg.CosNaming._NamingContextStub.resolve(_NamingContextStub.java:244)
       at com.sun.jndi.cosnaming.CNCtx.callResolve(CNCtx.java:501)
       at com.sun.jndi.cosnaming.CNCtx.lookup(CNCtx.java:555)
       at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
       at javax.naming.InitialContext.lookup(InitialContext.java:417)
       at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
       at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
       at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
       at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
       at io.prometheus.jmx.TestClass.doScrape(TestClass.java:46)
       at io.prometheus.jmx.TestClass.main(TestClass.java:22)

**Comment by abhishekgupte999** [comment]
This is how my Start.sh looks like 

#!/bin/sh

if [ -z "$SERVICE_PORT" ]; then
  SERVICE_PORT=5556
fi

if [ -z "$JVM_OPTS" ]; then
  JVM_OPTS="-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=5555 -Djmx.remote.protocol.provider.pkgs=weblogic.management.remote"
fi

if [ -z "$CONFIG_YML" ]; then
  CONFIG_YML=/opt/jmx_exporter/config.yml
fi

#java $JVM_OPTS -jar /opt/jmx_exporter/jmx_prometheus_httpserver-$VERSION-jar-with-dependencies.jar  $SERVICE_PORT $CONFIG_YML 

java $JVM_OPTS -classpath /opt/jmx_exporter/weblogic.jar:/opt/jmx_exporter/wljmxclient.jar:/opt/jmx_exporter/wlfullclient.jar:/opt/jmx_exporter/jmx_prometheus_httpserver-$VERSION-jar-with-dependencies.jar io.prometheus.jmx.WebServer $SERVICE_PORT $CONFIG_YML

**Comment by abhishekgupte999** [comment]
this is how my DockerFile looks like,
FROM anapsix/alpine-java:8
MAINTAINER sscaling <sscaling@users.noreply.github.com>

RUN apk update && apk upgrade && apk --update add curl && rm -rf /tmp/* /var/cache/apk/*

ENV VERSION 0.11.0
ENV JAR jmx_prometheus_httpserver-$VERSION-jar-with-dependencies.jar

RUN curl --insecure -L https://github.com/Yelp/dumb-init/releases/download/v1.2.1/dumb-init_1.2.1_amd64 -o usr/local/bin/dumb-init && chmod +x /usr/local/bin/dumb-init

RUN mkdir -p /opt/jmx_exporter
RUN curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_httpserver/$VERSION/$JAR -o /opt/jmx_exporter/$JAR
COPY start.sh /opt/jmx_exporter/
COPY config.yml /opt/jmx_exporter/
COPY wljmxclient.jar /opt/jmx_exporter/
COPY wlfullclient.jar /opt/jmx_exporter/
COPY weblogic.jar /opt/jmx_exporter/

RUN chown -R root /opt/jmx_exporter/
RUN chmod -R go-w /opt/jmx_exporter/


CMD ["usr/local/bin/dumb-init", "/opt/jmx_exporter/start.sh"]

**Comment by abhishekgupte999** [comment]
and here is my config file,

jmxUrl: service:jmx:rmi:///jndi/iiop://10.91.106.25:7001/weblogic.management.mbeanservers.runtime
username: admin
password: admin123
ssl: false 
lowercaseOutputName: false 
lowercaseOutputLabelNames: false 
whitelistObjectNames: 
  - "com.fundtech.util:Gpp_Logs_Manager=*,Type=GPP_LOGS,*"
  - "javax.management.notification:Gpp_Logs_Manager=*,Type=GPP_LOGS,*"  
  - "com.bea:Type=ServletRuntime,*" 
 
rules: 
  - pattern: ".*" 
    attrNameSnakeCase: false 
    name: weblogic_jmx_test1
    value: 05
    type: GAUGE
    labels:
      name: test 
      app: test1
      servletName: test3
 
  - pattern: "com.fundtech.util<message=(.+)><>(.+): (.+)"
    attrNameSnakeCase: false
    name: weblogic_jmx_test2
    value: 10
    type: GAUGE
    labels:
      name: $1
      app: $2
      servletName: $3

**Comment by abhishekgupte999** [comment]
Oct 18, 2019 5:19:13,821 PM IST> <Warning> <RMI> <BEA-080003> <A RuntimeException was generated by the RMI server: weblogic.corba.cos.naming.NamingContextImpl.resolve([Lorg.omg.CosNaming.NameComponent;)
 org.omg.CORBA.NO_PERMISSION: User <anonymous> does not have permission on weblogic.management.mbeanservers to perform lookup operation.  vmcid: 0x0  minor code: 0  completed: No.
org.omg.CORBA.NO_PERMISSION: User <anonymous> does not have permission on weblogic.management.mbeanservers to perform lookup operation.  vmcid: 0x0  minor code: 0  completed: No
	at weblogic.corba.cos.naming.NamingContextImpl.throwNamingException(NamingContextImpl.java:522)
	at weblogic.corba.cos.naming.NamingContextImpl.resolve(NamingContextImpl.java:189)
	at weblogic.corba.cos.naming._NamingContextAnyImplBase._invoke(_NamingContextAnyImplBase.java:306)
	at weblogic.corba.idl.CorbaServerRef.invoke(CorbaServerRef.java:240)
	at weblogic.rmi.cluster.ClusterableServerRef.invoke(ClusterableServerRef.java:246)
	Truncated. see log file for complete stacktrace
Caused By: javax.naming.NoPermissionException: User <anonymous> does not have permission on weblogic.management.mbeanservers to perform lookup operation.
	at weblogic.jndi.internal.ServerNamingNode.checkPermission(ServerNamingNode.java:485)
	at weblogic.jndi.internal.ServerNamingNode.checkLookup(ServerNamingNode.java:457)
	at weblogic.jndi.internal.ServerNamingNode.lookupHere(ServerNamingNode.java:225)
	at weblogic.jndi.internal.BasicNamingNode.lookupSharable(BasicNamingNode.java:1569)
	at weblogic.jndi.internal.BasicNamingNode.lookupSharable(BasicNamingNode.java:1583)
	Truncated. see log file for complete stacktrace

**Comment by abhishekgupte999** [comment]
Need help with above describe error.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
