### ISSUE TITLE
JMX Exporter can not collect Apache Ignite (v2.8.0) metrics

### ISSUE THREAD

**Issue by bostonaqua** [prometheus/jmx_exporter#483]
Hello,

the jmx_exporter can not collect most part of metrics after Apache Ignite 2.8.0 release. It worked with 2.7.0 but it doesn't now. Hope you can help me. So let me describe my problem:

First of all I'm using docker to run Apache Ignite, expose all ports on host system and add jmx_prometheus_javaagent: 
`docker run -it --net=host -e "CONFIG_URI=https://raw.githubusercontent.com/bostonaqua/bostonaqua/master/example-ignite.xml" -e "JAVA_TOOL_OPTIONS=-javaagent:/prometheus/jmx_prometheus_javaagent-0.12.0.jar=9091:/prometheus/ignite-config.yaml" -v $(pwd)/ignite-config.yaml:/prometheus/ignite-config.yaml -v $(pwd)/jmx_prometheus_javaagent-0.12.0.jar:/prometheus/jmx_prometheus_javaagent-0.12.0.jar apacheignite/ignite:2.8.0`

https://raw.githubusercontent.com/bostonaqua/bostonaqua/master/example-ignite.xml - here I enable the ignite metric exporter as described in docs: https://apacheignite.readme.io/docs/new-metrics

My prometheus/ignite-config.yaml:
```
hostPort: 127.0.0.1:49112
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
  - pattern: "^org.apache<clsLdr=(.+), group=cache,*"
```

Then I go to http://localhost:9091/ and get only jvm metrics.
Ok, lets look at logs:
```
[20:40:33,218][SEVERE][pool-1-thread-1][JmxCollector] JMX scrape failed: java.lang.ClassCastException: javax.management.openmbean.TabularDataSupport cannot be cast to javax.management.Attribute
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:156)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:468)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:59)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[20:40:33,416][SEVERE][pool-1-thread-2][JmxCollector] JMX scrape failed: java.lang.ClassCastException: javax.management.openmbean.TabularDataSupport cannot be cast to javax.management.Attribute
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:156)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:468)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:59)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Then I ran jmx_prometheus_httpserver-0.12.0-jar-with-dependencies.jar to get more info with logging level=all:
```
...
Apr 04, 2020 11:36:45 PM io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridIgfsExecutor'_'RejectedExecutionHandlerClass': process
Apr 04, 2020 11:36:45 PM io.prometheus.jmx.JmxScraper logScrape
FINE: scrape: 'org.apache{clsLdr=18b4aac2, group="Thread Pools", name=GridIgfsExecutor}RejectedExecutionHandlerClass': java.util.concurrent.ThreadPoolExecutor$AbortPolicy
Apr 04, 2020 11:36:45 PM io.prometheus.jmx.JmxScraper doScrape
FINE: TIME: 38508589 ns for org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridIgfsExecutor
Apr 04, 2020 11:36:45 PM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.ClassCastException: javax.management.openmbean.TabularDataSupport cannot be cast to javax.management.Attribute
	at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:156)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:468)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
...
```
The same, but some objects are scraped.
Maybe bad data? But I got these metrics from jconsole:
![ignite28](https://user-images.githubusercontent.com/36556520/78461171-77e49b80-76cf-11ea-86ab-0e6b3439cd71.png)
![ignite280](https://user-images.githubusercontent.com/36556520/78461173-7c10b900-76cf-11ea-9ef0-1fa5a6b76de4.png)

I'm not a java developer and would be great if you can help me. Thanks.

**Comment by brian-brazil** [comment]
This sounds like a bug with your software, as the bean is returning non-attributes from the getAttributes call.

**Comment by bostonaqua** [comment]
@brian-brazil but why any other jmx monitoring tool returns me attributes?
One more example with jmxterm:

```
bash-4.4# java -jar jmxterm.jar --url localhost:49112
Welcome to JMX terminal. Type "help" for available commands.

$>domains
#following domains are available
JMImplementation
com.sun.management
java.lang
java.nio
java.util.logging
org.apache
$>
$>domain org.apache
#domain is set to org.apache

$>beans
#domain = org.apache:
org.apache:clsLdr=18b4aac2,group="SQL Query",name=SqlQueryMXBeanImpl
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridAffinityExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridCallbackExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridClassLoadingExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridDataStreamExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridExecutionExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridIgfsExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridIndexingExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridManagementExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridQueryExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridRebalanceExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridRebalanceStripedExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridRestExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridSchemaExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridServicesExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridSystemExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=GridUtilityCacheExecutor
org.apache:clsLdr=18b4aac2,group="Thread Pools",name=StripedExecutor
org.apache:clsLdr=18b4aac2,group=Baseline,name=BaselineAutoAdjustMXBeanImpl
org.apache:clsLdr=18b4aac2,group=Clients,name=ClientListenerProcessor
org.apache:clsLdr=18b4aac2,group=DataRegionMetrics,name=TxLog
org.apache:clsLdr=18b4aac2,group=DataRegionMetrics,name=default
org.apache:clsLdr=18b4aac2,group=DataRegionMetrics,name=sysMemPlc
org.apache:clsLdr=18b4aac2,group=DataStorage,name=DataStorageMXBeanImpl
org.apache:clsLdr=18b4aac2,group=Diagnostic,name=PageLockTracker
org.apache:clsLdr=18b4aac2,group=Kernal,name=ClusterLocalNodeMetricsMXBeanImpl
org.apache:clsLdr=18b4aac2,group=Kernal,name=ClusterMetricsMXBeanImpl
org.apache:clsLdr=18b4aac2,group=Kernal,name=FailureHandlingMxBeanImpl
org.apache:clsLdr=18b4aac2,group=Kernal,name=IgniteKernal
org.apache:clsLdr=18b4aac2,group=Kernal,name=Ignition
org.apache:clsLdr=18b4aac2,group=Metrics,name=MetricsMxBeanImpl
org.apache:clsLdr=18b4aac2,group=SPIs,name=AlwaysFailoverSpi
org.apache:clsLdr=18b4aac2,group=SPIs,name=LocalDeploymentSpi
org.apache:clsLdr=18b4aac2,group=SPIs,name=RoundRobinLoadBalancingSpi
org.apache:clsLdr=18b4aac2,group=SPIs,name=TcpCommunicationSpi
org.apache:clsLdr=18b4aac2,group=SPIs,name=TcpDiscoverySpi
org.apache:clsLdr=18b4aac2,group=TransactionMetrics,name=TransactionMetricsMxBeanImpl
org.apache:clsLdr=18b4aac2,group=Transactions,name=TransactionsMXBeanImpl
org.apache:clsLdr=18b4aac2,group=cache,name="ignite-sys-cache"
org.apache:clsLdr=18b4aac2,group=cacheGroups,name="ignite-sys-cache"
org.apache:clsLdr=18b4aac2,group=communication,name=tcp
org.apache:clsLdr=18b4aac2,group=compute,name=jobs
org.apache:clsLdr=18b4aac2,group=io,name="dataregion.TxLog"
org.apache:clsLdr=18b4aac2,group=io,name="dataregion.default"
org.apache:clsLdr=18b4aac2,group=io,name="dataregion.sysMemPlc"
org.apache:clsLdr=18b4aac2,group=io,name=communication
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridAffinityExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridCallbackExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridClassLoadingExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridDataStreamExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridExecutionExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridIgfsExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridIndexingExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridManagementExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridQueryExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridRebalanceExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridRebalanceStripedExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridRestExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridSchemaExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridServicesExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridSystemExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=GridUtilityCacheExecutor
org.apache:clsLdr=18b4aac2,group=threadPools,name=StripedExecutor
org.apache:clsLdr=18b4aac2,group=views,name="client.connections"
org.apache:clsLdr=18b4aac2,group=views,name="continuous.queries"
org.apache:clsLdr=18b4aac2,group=views,name="datastream.threadpool.queue"
org.apache:clsLdr=18b4aac2,group=views,name="scan.queries"
org.apache:clsLdr=18b4aac2,group=views,name="sql.queries"
org.apache:clsLdr=18b4aac2,group=views,name="sql.queries.history"
org.apache:clsLdr=18b4aac2,group=views,name="striped.threadpool.queue"
org.apache:clsLdr=18b4aac2,group=views,name="table.columns"
org.apache:clsLdr=18b4aac2,group=views,name="view.columns"
org.apache:clsLdr=18b4aac2,group=views,name=cacheGroups
org.apache:clsLdr=18b4aac2,group=views,name=caches
org.apache:clsLdr=18b4aac2,group=views,name=indexes
org.apache:clsLdr=18b4aac2,group=views,name=nodes
org.apache:clsLdr=18b4aac2,group=views,name=schemas
org.apache:clsLdr=18b4aac2,group=views,name=services
org.apache:clsLdr=18b4aac2,group=views,name=tables
org.apache:clsLdr=18b4aac2,group=views,name=tasks
org.apache:clsLdr=18b4aac2,group=views,name=transactions
org.apache:clsLdr=18b4aac2,group=views,name=views
org.apache:clsLdr=18b4aac2,name=cache
org.apache:clsLdr=18b4aac2,name=pme
org.apache:clsLdr=18b4aac2,name=sys
org.apache:clsLdr=18b4aac2,name=tx

$>bean org.apache:clsLdr=18b4aac2,group=cache,name="ignite-sys-cache"
#bean is set to org.apache:clsLdr=18b4aac2,group=cache,name="ignite-sys-cache"

$>info
#mbean = org.apache:clsLdr=18b4aac2,group=cache,name="ignite-sys-cache"
#class name = org.apache.ignite.spi.metric.ReadOnlyMetricManager
# attributes
  %0   - CacheEvictions (java.lang.Long, r)
  %1   - CacheGets (java.lang.Long, r)
  %2   - CacheHits (java.lang.Long, r)
  %3   - CacheMisses (java.lang.Long, r)
  %4   - CachePuts (java.lang.Long, r)
  %5   - CacheRemovals (java.lang.Long, r)
  %6   - CacheTxCommits (java.lang.Long, r)
  %7   - CacheTxRollbacks (java.lang.Long, r)
  %8   - CommitTime (java.lang.Long, r)
  %9   - EntryProcessorHits (java.lang.Long, r)
  %10  - EntryProcessorInvokeTimeNanos (java.lang.Long, r)
  %11  - EntryProcessorMaxInvocationTime (java.lang.Long, r)
  %12  - EntryProcessorMinInvocationTime (java.lang.Long, r)
  %13  - EntryProcessorMisses (java.lang.Long, r)
  %14  - EntryProcessorPuts (java.lang.Long, r)
  %15  - EntryProcessorReadOnlyInvocations (java.lang.Long, r)
  %16  - EntryProcessorRemovals (java.lang.Long, r)
  %17  - EstimatedRebalancingKeys (java.lang.Long, r)
  %18  - GetTimeTotal (java.lang.Long, r)
  %19  - GetTime_0_1000000 (java.lang.Long, r)
  %20  - GetTime_1000000000_inf (java.lang.Long, r)
  %21  - GetTime_100000000_250000000 (java.lang.Long, r)
  %22  - GetTime_10000000_100000000 (java.lang.Long, r)
  %23  - GetTime_1000000_10000000 (java.lang.Long, r)
  %24  - GetTime_250000000_1000000000 (java.lang.Long, r)
  %25  - IsIndexRebuildInProgress (java.lang.Boolean, r)
  %26  - OffHeapEvictions (java.lang.Long, r)
  %27  - OffHeapGets (java.lang.Long, r)
  %28  - OffHeapHits (java.lang.Long, r)
  %29  - OffHeapMisses (java.lang.Long, r)
  %30  - OffHeapPuts (java.lang.Long, r)
  %31  - OffHeapRemovals (java.lang.Long, r)
  %32  - PutTimeTotal (java.lang.Long, r)
  %33  - PutTime_0_1000000 (java.lang.Long, r)
  %34  - PutTime_1000000000_inf (java.lang.Long, r)
  %35  - PutTime_100000000_250000000 (java.lang.Long, r)
  %36  - PutTime_10000000_100000000 (java.lang.Long, r)
  %37  - PutTime_1000000_10000000 (java.lang.Long, r)
  %38  - PutTime_250000000_1000000000 (java.lang.Long, r)
  %39  - QueryCompleted (java.lang.Long, r)
  %40  - QueryExecuted (java.lang.Long, r)
  %41  - QueryFailed (java.lang.Long, r)
  %42  - QueryMaximumTime (java.lang.Long, r)
  %43  - QueryMinimalTime (java.lang.Long, r)
  %44  - QuerySumTime (java.lang.Long, r)
  %45  - RebalanceClearingPartitionsLeft (java.lang.Long, r)
  %46  - RebalanceStartTime (java.lang.Long, r)
  %47  - RebalancedKeys (java.lang.Long, r)
  %48  - RebalancingBytesRate (java.lang.Long, r)
  %49  - RebalancingKeysRate (java.lang.Long, r)
  %50  - RemoveTimeTotal (java.lang.Long, r)
  %51  - RemoveTime_0_1000000 (java.lang.Long, r)
  %52  - RemoveTime_1000000000_inf (java.lang.Long, r)
  %53  - RemoveTime_100000000_250000000 (java.lang.Long, r)
  %54  - RemoveTime_10000000_100000000 (java.lang.Long, r)
  %55  - RemoveTime_1000000_10000000 (java.lang.Long, r)
  %56  - RemoveTime_250000000_1000000000 (java.lang.Long, r)
  %57  - RollbackTime (java.lang.Long, r)
  %58  - TotalRebalancedBytes (java.lang.Long, r)
#there's no operations
#there's no notifications

$>get CacheGets
#mbean = org.apache:clsLdr=18b4aac2,group=cache,name="ignite-sys-cache":
CacheGets = 0;
```

Everywhere it represented as attributes.
I use official docker image from Apache.

**Comment by brian-brazil** [comment]
Other tools may have code to deal with bad data. If a piece of software is sufficiently broken so as to break Java's type system - which is what appears to be going on here, this exception should be impossible - that's a bug with the software not with this exporter.

**Comment by alkoclick** [comment]
I am also experiencing this issue and I'm not sure if the cause is "bad data". It can manifest in 2 forms (besides the one already presented in the post):

```
SEVERE: JMX scrape failed: java.lang.IllegalArgumentException: Not an Attribute: javax.management.openmbean.TabularDataSupport(tabularType=javax.management.openmbean.TabularType(name=org.apache.ignite.spi.systemview.view.ClientConnectionView,rowType=javax.management.openmbean.CompositeType(name=org.apache.ignite.spi.systemview.view.ClientConnectionView,items=((itemName=connectionId,itemType=javax.management.openmbean.SimpleType(name=java.lang.Long)),(itemName=localAddress,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=remoteAddress,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=systemViewRowId,itemType=javax.management.openmbean.SimpleType(name=java.lang.Integer)),(itemName=type,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=user,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)),(itemName=version,itemType=javax.management.openmbean.SimpleType(name=java.lang.String)))),indexNames=(systemViewRowId)),contents={}

```

and 

```
May 17, 2020 7:47:37 PM io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.lang.IllegalArgumentException: Not an Attribute: -348193424
```
Where the actual value in "Not an attribute" can be any int, from what I've seen


It seems to be related to: https://apacheignite.readme.io/docs/system-views but I can't for the life of me properly ignore it either on the jmx exporter side, or the ignite side

**Comment by alkoclick** [comment]
I've followed up on this thread because it's at the top of Google results and seems to be the most relevant. Let me know if you'd like to open a new issue for this.

I've currently resolved my problem by disabling all Ignite exported metrics:
```java
var systemViewExporter = new JmxSystemViewExporterSpi();
systemViewExporter.setExportFilter( (__) -> false);

var metricExporter = new JmxMetricExporterSpi();
metricExporter.setExportFilter( (__) -> false);

new IgniteConfiguration()
        .setSystemViewExporterSpi(systemViewExporter)
        .setMetricExporterSpi(metricExporter);
```

**Comment by piotrkrokowski** [comment]
> Other tools may have code to deal with bad data. If a piece of software is sufficiently broken so as to break Java's type system - which is what appears to be going on here, this exception should be impossible - that's a bug with the software not with this exporter.

Well - where to start. This kind of attitude made me actually log in and comment on this. 
Firstly - this could be an issue with the framework used by the application that's being monitored, not within the application (as it is in my case - the "bug" is in Wildfly 10).
Secondly - playing "blame game", instead of just trying to improve the solution isn't going to take you anywhere. Bug or feature - regardless - this should be improved.
Thirdly - not handling exceptions that actually do happen in real world and not allowing user to filter out invalid data IS a bug for me.

I'd vote for simply catching such exceptions and ignoring invalid data. I'm sincerely surprised this never crossed your mind.
As result, we might be forced to fork the code just to catch such exception, as it's not possible for me to fix it in third party code...
