### ISSUE TITLE
FATAL ERROR in native method: processing of -javaagent failed

### ISSUE THREAD

**Issue by abhishekkarigar** [prometheus/jmx_exporter#484]
running kafka, zookeeper with prometheus  
following is the error i get when i try to produce data from kafka container

bash-4.4# kafka-console-producer.sh --broker-list localhost:9094 --topic myTopic
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.net.BindException: Address in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)
        at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:31)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by theRealWardo** [comment]
in case this helps another future Google searcher... you need to figure out what env var is setting your `-javaagent` flag. given you are also using the jmx exporter with kafka, I have seen this set as either `KAFKA_OPTS` or `KAFKA_JVM_PERFORMANCE_OPTS`. to use the scripts that come with kafka you want to `unset` those env vars or you can clear the env var inline like:
```
KAFKA_JVM_PERFORMANCE_OPTS="" JMX_PORT=1234 kafka-topics.sh --zookeeper ${KAFKA_ZOOKEEPER_CONNECT} --list
```

note that you will have to still specify an alternative `JMX_PORT` if you are executing the command inside of a kafka container that has a running jmx exporter.
