### ISSUE TITLE
Wildfly swarm crashes when use JMX exporter

### ISSUE THREAD

**Issue by ca7erina** [prometheus/jmx_exporter#505]
I acutally have been using this JMX exporter with many projects, they are all good. However, when I use it with wildfly swarm project
`java -javaagent:./jmx_prometheus_javaagent-0.13.0.jar=5556:config.yaml -jar -Xdebug myproject-xx-swarm.jar -Sgenius  `

The application crash, and here is this Error :
```Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                   JSON-P - STABLE          org.wildfly.swarm:jsonp:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:        CDI Configuration - STABLE          org.wildfly.swarm:cdi-config:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                      JCA - STABLE          org.wildfly.swarm:jca:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                    Batch - STABLE          org.wildfly.swarm:batch-jberet:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:              Datasources - STABLE          org.wildfly.swarm:datasources:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                     Mail - STABLE          org.wildfly.swarm:mail:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2017.9.4
Jun 18, 2020 6:09:01 PM org.wildfly.swarm.container.runtime.ServerBootstrapImpl logFraction
INFO: WFSWARM0013: Installed fraction:                   JAX-RS - STABLE          org.wildfly.swarm:jaxrs:2017.9.4
Jun 18, 2020 6:09:01 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.3.5 (Final)
Jun 18, 2020 6:09:01 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 18, 2020 6:09:01 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Jun 18, 2020 6:09:01 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] org.wildfly.swarm.container.runtime.cdi.ImplicitArchiveExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Jun 18, 2020 6:09:02 PM org.jboss.weld.interceptor.reader.InterceptorMetadataUtils isValidTargetClassLifecycleInterceptorMethod
WARN: WELD-001471: Interceptor method setupFactories defined on class org.wildfly.swarm.container.runtime.xmlconfig.StandaloneXMLParserProducer is not defined according to the specification. It should not throw java.lang.Exception, which is a checked exception.
	at org.wildfly.swarm.container.runtime.xmlconfig.StandaloneXMLParserProducer.setupFactories(StandaloneXMLParserProducer.java:0)
  StackTrace
Jun 18, 2020 6:09:02 PM org.jboss.weld.environment.se.WeldContainer initialize
INFO: WELD-ENV-002003: Weld SE container internal initialized
Jun 18, 2020 6:09:02 PM org.wildfly.swarm.datasources.runtime.DatasourceAndDriverCustomizer attemptInstallation
INFO: WFSWARM1003: Auto-detected JDBC driver for sqlserver
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:114)
	at org.wildfly.swarm.Swarm.start(Swarm.java:375)
	at org.wildfly.swarm.Swarm.main(Swarm.java:631)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.wildfly.swarm.logging.runtime.EarlyLoggingCustomizer.customize(EarlyLoggingCustomizer.java:44)
	at org.wildfly.swarm.logging.runtime.EarlyLoggingCustomizer$Proxy$_$$_WeldClientProxy.customize(Unknown Source)
	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:165)
	at org.wildfly.swarm.container.runtime.RuntimeServer$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$bootstrap$1(ServerBootstrapImpl.java:160)
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:43)
	... 10 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:114)
	at org.wildfly.swarm.Swarm.start(Swarm.java:375)
	at org.wildfly.swarm.Swarm.main(Swarm.java:631)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.wildfly.swarm.logging.runtime.EarlyLoggingCustomizer.customize(EarlyLoggingCustomizer.java:44)
	at org.wildfly.swarm.logging.runtime.EarlyLoggingCustomizer$Proxy$_$$_WeldClientProxy.customize(Unknown Source)
	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:165)
	at org.wildfly.swarm.container.runtime.RuntimeServer$Proxy$_$$_WeldClientProxy.start(Unknown Source)
	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$bootstrap$1(ServerBootstrapImpl.java:160)
	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:43)
	... 10 more
```

**Comment by brian-brazil** [comment]
I see nothing there related to the JMX exporter, which only performs simple calls to the mBeans exposed by the application. This is a bug in your applicaiton.

**Comment by ca7erina** [comment]
@brian-brazil You are right! That's not the a jmx exporter bug, after i configured a ```-Djava.util.logging.manager```, it's all good now, thanks for replying!
