### ISSUE TITLE
runs in ubuntu but causes exception in container(s)

### ISSUE THREAD

**Issue by jstockmi** [prometheus/jmx_exporter#551]
using the v14 downloaded jar  from prometheus github
created dockerfile:

 cat dockerfile
#FROM openjdk:latest
FROM openjdk:8-jre-slim
#RUN mkdir /usr/src
RUN mkdir /usr/src/myapp
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
#RUN ls
#RUN javac -d . Hello.java
#RUN ls
#RUN jar cvf Hello.jar Hello.class
#RUN ls
#RUN jar cvmf MANIFEST.MF Hello.jar Hello.class
#RUN ls
#RUN echo "listing important contents"
#
RUN apt-get update && apt-get update -y && apt-get update

RUN ls -ltr
RUN sleep 01
CMD ["java", "-javaagent:/usr/src/myapp/jmx_prometheus_javaagent-0.14.0.jar=8080:/usr/src/myapp/onfig.yml -jar /usr/src/myapp//Hello.jar"]

Fails i cntainer with:

~/jmx/try1/jmx_exporter$ docker run -p 5556:5556 hellojmx
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.FileNotFoundException: /usr/src/myapp/onfig.yml -jar /usr/src/myapp/Hello.jar (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)FATAL ERROR in native method: processing of -javaagent failed

        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
        ... 6 more
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fea5c178611, pid=1, tid=0x00007fea5afbd700
#
# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.272-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x22611]  abort+0x1fd
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/src/myapp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jstockmi** [comment]
add insetad of copy in dockerfile
then the run command was wrong too ...

**Comment by jstockmi** [comment]
thanks for the sugg Brian.
but all good now, posting it raised my level of embarrassment to an intolerable level ...
fixed with a few more googles and cursing.
