### ISSUE TITLE
The port cannot be accessed when monitoring tomcat

### ISSUE THREAD

**Issue by lvguoqiang** [prometheus/jmx_exporter#559]
Thread information shows that it has been blocked

"prometheus-http-1-4" #50 daemon prio=5 os_prio=0 tid=0x00007f463c007000 nid=0x76f1 waiting for monitor entry [0x00007f45e1cee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at oracle.jdbc.driver.PhysicalConnection.isClosed(PhysicalConnection.java:5042)
        - waiting to lock <0x00000006c9eb3a48> (a oracle.jdbc.driver.T4CConnection)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.toString(DelegatingConnection.java:106)
        at org.apache.tomcat.dbcp.dbcp2.PoolableConnection.getToString(PoolableConnection.java:252)
        at sun.reflect.GeneratedMethodAccessor763.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
