### ISSUE TITLE
Unable to run jmx exporter on Windows 10

### ISSUE THREAD

**Issue by manuchadha1979** [prometheus/jmx_exporter#565]
I am trying to run jmx exporter on Windows 10. The steps in the README seem to be only for unix systems. My understanding is that to run javaagent on Windows, the bin/cassandra.bat file need to be changed

https://docs.appdynamics.com/display/PRO45/Apache+Cassandra+Startup+Settings

I made the following change to the .bat file  

-javaagent:"%CASSANDRA_HOME%\lib\jmx_prometheus_javaagent-0.3.0.jar=7070:%CASSANDRA_HOME%\cassandra.yml"

But I get error

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NumberFormatException: For input string: "C"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:38)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by manuchadha1979** [comment]
In case some comes looking, I got it working here - https://stackoverflow.com/questions/65357086/convert-a-sh-command-into-bat-equivalent
