### ISSUE TITLE
tomcat startup failed

### ISSUE THREAD

**Issue by zhangjian2xxx** [prometheus/jmx_exporter#591]
2021-03-17 14:16:06,274 [prometheus-http-1-3] ERROR servlet.GrailsDispatcherServlet  - Context initialization failed
java.lang.IllegalArgumentException: Grails requires a parent ApplicationContext, is the /WEB-INF/applicationContext.xml file missing?
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:151)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:158)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:73)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2021-03-17 14:16:06,280 [prometheus-http-1-3] ERROR servlet.ErrorHandlingServlet  - Context initialization failed
java.lang.IllegalArgumentException: Grails requires a parent ApplicationContext, is the /WEB-INF/applicationContext.xml file missing?
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:151)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:158)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:73)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2021-03-17 14:16:06,355 [prometheus-http-1-3] ERROR pages.GroovyPagesServlet  - Context initialization failed
java.lang.IllegalStateException: No WebApplicationContext found: initializer not registered?
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:151)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:117)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:158)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:73)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dhoard** [comment]
@zhangjian2xxx Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.
