### ISSUE TITLE
running as http server

### ISSUE THREAD

**Issue by f-adrian** [prometheus/jmx_exporter#629]
Hi,

Trying to run the jmx_exporter in httpd mode.
I'm getting the error below. Any ideas ?

Aug 18, 2021 9:45:15 AM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.lang.ClassNotFoundException: mx4j.tools.remote.rmi.SSLRMIClientSocketFactory (no security manager: RMI class loader disabled)]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
	at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:158)
	at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:84)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Running the scraper alone, I can see the metrics.
When running the scraper, I export my Java classpath to:

CLASSPATH=collector/target/collector-0.16.2-SNAPSHOT.jar:lib/mx4j-tools-3.0.1.jar

thanks,
Adrian

**Comment by f-adrian** [comment]
Apparently is OK now after adding the mx4j tools to the collector's pom.xml

**Comment by dhoard** [comment]
Closing this issue as resolved.
