### ISSUE TITLE
Issue with setting up jmx_exporter with kafka and zookeeper

### ISSUE THREAD

**Issue by sunnythepatel** [prometheus/jmx_exporter#639]
Hi Team,
   I am facing an error in setting up the jmx_exporter

```
 sudo systemctl status kafka
● kafka.service - Kafka
     Loaded: loaded (/etc/systemd/system/kafka.service; disabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2021-09-28 13:09:27 UTC; 2min 16s ago
    Process: 4109 ExecStart=/home/ubuntu/kafka/bin/kafka-server-start.sh /home/ubuntu/kafka/config/server.properties (code=killed, sign>
   Main PID: 4109 (code=killed, signal=ABRT)

Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.getSi>
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.org.yaml.snakeyaml.constructor.BaseConstru>
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.loadFromReader(Yam>
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.load(Yaml.java:442)
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxC>
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAg>
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]:         ... 6 more
Sep 28 13:09:27 zookeeper-2 kafka-server-start.sh[4109]: FATAL ERROR in native method: processing of -javaagent failed
Sep 28 13:09:27 zookeeper-2 systemd[1]: kafka.service: Main process exited, code=killed, status=6/ABRT
Sep 28 13:09:27 zookeeper-2 systemd[1]: kafka.service: Failed with result 'signal'.
```

```
ubuntu@zookeeper-2:~$ cat /etc/systemd/system/kafka.service
[Unit]
Description=Kafka
After=network.target

[Service]
User=ubuntu
Group=ubuntu
Environment="KAFKA_HEAP_OPTS=-Xmx256M -Xms128M"
Environment="KAFKA_OPTS=-javaagent:/home/ubuntu/prometheus/jmx_prometheus_javaagent-0.16.1.jar=8080:/home/ubuntu/prometheus/kafka-2_0_0.yml"
ExecStart=/home/ubuntu/kafka/bin/kafka-server-start.sh /home/ubuntu/kafka/config/server.properties
#ExecStart=/etc/init.d/kafka
ExecStop=/home/ubuntu/kafka/bin/kafka-server-stop.sh
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

```
ubuntu@zookeeper-2:~$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

I am not able to figure out the issue.  Any help will be much appreciated?

Thank you

**Comment by sunnythepatel** [comment]
Hi @fstab,
  I was able to figure out that thank you for your help but now I am getting his error

```
ubuntu@zookeeper-3:~/prometheus$ sudo systemctl status kafka
● kafka.service - Kafka
     Loaded: loaded (/etc/systemd/system/kafka.service; disabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2021-09-28 14:21:25 UTC; 56s ago
    Process: 22218 ExecStart=/home/ubuntu/kafka/bin/kafka-server-start.sh /home/ubuntu/kafka/config/server.properties (code=kille>
   Main PID: 22218 (code=killed, signal=ABRT)

Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java>
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at sun.net.httpserver.DefaultHttpServerProvider.createHttpServe>
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPS>
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain>
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]:         ... 6 more
Sep 28 14:21:25 zookeeper-3 kafka-server-start.sh[22218]: FATAL ERROR in native method: processing of -javaagent failed
Sep 28 14:21:25 zookeeper-3 systemd[1]: kafka.service: Main process exited, code=killed, status=6/ABRT
Sep 28 14:21:25 zookeeper-3 systemd[1]: kafka.service: Failed with result 'signal'.
```

```
ubuntu@zookeeper-3:~/prometheus$ cat kafka-2_0_0.yml
lowercaseOutputName: true

rules:
# Special cases and very specific rules
- pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    clientId: "$3"
    topic: "$4"
    partition: "$5"
- pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
  name: kafka_server_$1_$2
  type: GAUGE
  labels:
    clientId: "$3"
    broker: "$4:$5"
- pattern : kafka.coordinator.(\w+)<type=(.+), name=(.+)><>Value
  name: kafka_coordinator_$1_$2_$3
  type: GAUGE

# Generic per-second counters with 0-2 key/value pairs
- pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
  name: kafka_$1_$2_$3_total
  type: COUNTER
  labels:
    "$4": "$5"
    "$6": "$7"
- pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count
  name: kafka_$1_$2_$3_total
  type: COUNTER
  labels:
    "$4": "$5"
- pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
  name: kafka_$1_$2_$3_total
  type: COUNTER

- pattern: kafka.server<type=(.+), client-id=(.+)><>([a-z-]+)
  name: kafka_server_quota_$3
  type: GAUGE
  labels:
    resource: "$1"
    clientId: "$2"

- pattern: kafka.server<type=(.+), user=(.+), client-id=(.+)><>([a-z-]+)
  name: kafka_server_quota_$4
  type: GAUGE
  labels:
    resource: "$1"
    user: "$2"
    clientId: "$3"

# Generic gauges with 0-2 key/value pairs
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value
  name: kafka_$1_$2_$3
  type: GAUGE
  labels:
    "$4": "$5"
    "$6": "$7"
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
  name: kafka_$1_$2_$3
  type: GAUGE
  labels:
    "$4": "$5"
- pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
  name: kafka_$1_$2_$3
  type: GAUGE

# Emulate Prometheus 'Summary' metrics for the exported 'Histogram's.
#
# Note that these are missing the '_sum' metric!
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count
  name: kafka_$1_$2_$3_count
  type: COUNTER
  labels:
    "$4": "$5"
    "$6": "$7"
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*), (.+)=(.+)><>(\d+)thPercentile
  name: kafka_$1_$2_$3
  type: GAUGE
  labels:
    "$4": "$5"
    "$6": "$7"
    quantile: "0.$8"
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count
  name: kafka_$1_$2_$3_count
  type: COUNTER
  labels:
    "$4": "$5"
- pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile
  name: kafka_$1_$2_$3
  type: GAUGE
  labels:
    "$4": "$5"
    quantile: "0.$6"
- pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
  name: kafka_$1_$2_$3_count
  type: COUNTER
- pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
  name: kafka_$1_$2_$3
  type: GAUGE
  labels:
    quantile: "0.$4"
```


Thank you

**Comment by fstab** [comment]
I have to guess because the stack traces are truncated, but as it's coming from the `HTTPServer`, maybe the port is already in use?

**Comment by sunnythepatel** [comment]
Hi @fstab ,
  Isn't it should be used by java if i kill it, it gives me other issues

```
ubuntu@zookeeper-2:~$ sudo netstat -anpe | grep "8080" | grep "LISTEN"
tcp6       0      0 :::8080                 :::*                    LISTEN      0          30453      2641/java
```

**Comment by fstab** [comment]
Just try another port, in `/etc/systemd/system/kafka.service` replace `8080` in `KAFKA_OPTS` with another number, like 12345.

**Comment by sunnythepatel** [comment]
Thank you @fstab  it works

**Comment by sunnythepatel** [comment]
Hi @fstab,
  I am sorry any idea how to fix this issue zookeeper and Kafka using the same jar and I have changed the port number
```
ubuntu@zookeeper-1:~/prometheus$ sudo systemctl status zookeeper
● zookeeper.service - Zookeeper
     Loaded: loaded (/etc/systemd/system/zookeeper.service; disabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2021-09-28 23:56:32 UTC; 2s ago
    Process: 334997 ExecStart=/home/ubuntu/kafka/bin/zookeeper-server-start.sh /home/ubuntu/kafka/config/zookeeper.properties (code=killed, signal=ABRT)
   Main PID: 334997 (code=killed, signal=ABRT)

Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at java.io.FileInputStream.open0(Native Method)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at java.io.FileInputStream.open(FileInputStream.java:195)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at java.io.FileInputStream.<init>(FileInputStream.java:138)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at java.io.FileReader.<init>(FileReader.java:72)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]:         ... 6 more
Sep 28 23:56:32 zookeeper-1 zookeeper[334997]: FATAL ERROR in native method: processing of -javaagent failed
Sep 28 23:56:32 zookeeper-1 systemd[1]: zookeeper.service: Main process exited, code=killed, status=6/ABRT
Sep 28 23:56:32 zookeeper-1 systemd[1]: zookeeper.service: Failed with result 'signal'.
```

```
[Unit]
Description=Zookeeper
After=network.target

[Service]
User=root
Group=root
SyslogIdentifier=zookeeper
Environment="KAFKA_OPTS=-javaagent:/home/ubuntu/prometheus/jmx_prometheus_javaagent-0.16.1.jar=8081:/home/ubuntu/prometheus/zookeeper.yml"
ExecStart=/home/ubuntu/kafka/bin/zookeeper-server-start.sh /home/ubuntu/kafka/config/zookeeper.properties
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

**Comment by sunnythepatel** [comment]
Hi @fstab,
  I was able to find an error using journalctl -u zookeeper and fix it. There was a spelling mistake while mentioning the zookeeper.yaml. I had mentioned zookeeper.yml

```
Unit]
Description=Zookeeper
After=network.target

[Service]
User=root
Group=root
SyslogIdentifier=zookeeper
Environment="EXTRA_ARGS=-javaagent:/home/ubuntu/prometheus/jmx_prometheus_javaagent-0.16.1.jar=8081:/home/ubuntu/prometheus/zookeeper.yaml"
ExecStart=/home/ubuntu/kafka/bin/zookeeper-server-start.sh /home/ubuntu/kafka/config/zookeeper.properties
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```
