### ISSUE TITLE
FATAL ERROR in native method: processing of -javaagent failed (Caused by: java.net.BindException: Address already in use)

### ISSUE THREAD

**Issue by Anshuamrita** [prometheus/jmx_exporter#647]
**Getting this error when performing operation for application running on Jboss**

Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
**Caused by: java.net.BindException: Address already in use**
at sun.nio.ch.Net.bind0(Native Method)
at sun.nio.ch.Net.bind(Net.java:461)
at sun.nio.ch.Net.bind(Net.java:453)
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
at sun.net.httpserver.ServerImpl.(ServerImpl.java:100)
at sun.net.httpserver.HttpServerImpl.(HttpServerImpl.java:50)
at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.(HTTPServer.java:190)
at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:31)

_Currently I have specified javaagent as
javaagent:/jmx_prometheus_javaagent.jar=8686:/jmx_exporter.yaml_

**Comment by Tusharbeginner** [comment]
you can try to add specific JMX remote ports to this command

`javaagent:/jmx_prometheus_javaagent.jar=8686:/jmx_exporter.yaml -Dcom.sun.management.jmxremote.port=25000 -Dcom.sun.management.jmxremote.rmi.port=25000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=127.0.0.1`

Also, kill all the processes using these ports or change these ports to any other available ports before running this command.

**Comment by RootKaizer** [comment]
hello community,
I have implemented "jmx_prometheus_javaagent-0.12.0.jar" to monitor karaf, when I try to enter karaf with ./client command it replicates this error, I look for multiple solutions for this problem even I tried all the settings from this post but karaf keeps failing.

**Comment by dhoard** [comment]
@Anshuamrita  A **java.net.BindException: Address already in use** is caused because the JMX Exporter is trying to use a port already in use, which typically means there is a process already using the port.

Have you resolved this issue?

If there are no updates within 1 week, this will be closed as inactive.
