### ISSUE TITLE
Different Metrics depending of invokation

### ISSUE THREAD

**Issue by davidmpaz** [prometheus/jmx_exporter#666]
Hello,

first of all, thanks for this awesome project! 

I did ask the question in the [Google Mail Group](https://groups.google.com/g/prometheus-users/c/7Qe0LThXcJE/m/w-dRl8TJAAAJ) and since I did not get any answer and also since I think this is not a normal behaviour I will create this issue. 

Why I am getting different metrics when using the jmx agent and when using the jmx http server?

The configuration is always the same:
```yaml
---
hostPort: "host:1099"
username:
password:
rules:
- pattern: '.*'
...
```

As agent i am attaching it to a tomcat, as http server i am running it as:
`java -jar /opt/jmx/jmx-httpserver-0.16.2.jar 9099 /opt/jmx/tomcat.yml`

The tomcat server is startet always to expose jxm on port 1099.

Am I having wrong expectations or it is just simple plain ignorance? I would expect that at least one metric set superceed the other by overlapping it but not exposing muttually exclussive metrics.

Any feedback will be more than welcome.

Thanks again and cheers,
David

**Comment by fstab** [comment]
You don't need both, the agent and the HTTP server. You just need one of them.

* Agent: Attaches directly to the local JVM
* HTTP Server: Attaches to a remote JVM via remote JMX.

The `hostPort` configuration in the HTTP server says where to connect to via remote JMX. It is not where the agent exposes metrics via HTTP.

As you have the agent attached already, configure your Prometheus server to scrape the metrics from the agent. You don't need the HTTP server in that case.

**Comment by davidmpaz** [comment]
Hi @fstab,

thanks for answering. Yes you are right, and that's the case for me. I am not using them together, I wanted only to explain my findings, that when using one or the other i get different set of metrics exposed.

For example:

`java_lang_operatingsystem_availableprocessors{job="$job", instance="$instance"}`  does not get exported when using the jmx as agent, when i use it as http server, it does.

**Comment by fstab** [comment]
I tried to reproduce this with the example application in `./integration_tests/jmx_example_application`, but I'm seeing the metric no matter how I connect.

Remote:

1. Start the example application with remote JMX enabled on port 9999
    ```
    java -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar ./integration_tests/jmx_example_application/target/jmx_example_application.jar
    ```
2. Start the `jmx_exporter` HTTP server, connecting to port 9999
    ```
    java -jar ./jmx_prometheus_httpserver/target/jmx_prometheus_httpserver-0.16.2-SNAPSHOT-jar-with-dependencies.jar 9000 ./integration_tests/smoke_tests/src/test/resources/config-httpserver.yml
    ```
3. Scrape metrics
    ```
    curl -s http://localhost:9000/metrics | grep java_lang_OperatingSystem_AvailableProcessors
    ```

Via agent

1. Start Application with the `jmx_exporter` agent attached
    ```
    java -javaagent:$(pwd)/jmx_prometheus_javaagent/target/jmx_prometheus_javaagent-0.16.2-SNAPSHOT.jar=9090:$(pwd)/integration_tests/smoke_tests/src/test/resources/config.yml  -jar ./integration_tests/jmx_example_application/target/jmx_example_application.jar
    ```
2. Scrape metrics
    ```
    curl -s http://localhost:9090/metrics | grep java_lang_OperatingSystem_AvailableProcessors
    ```

Same result in both cases
```
# HELP java_lang_OperatingSystem_AvailableProcessors AvailableProcessors (java.lang<type=OperatingSystem><>AvailableProcessors)
# TYPE java_lang_OperatingSystem_AvailableProcessors untyped
java_lang_OperatingSystem_AvailableProcessors 8.0
```
Do you see what you do differently?

**Comment by davidmpaz** [comment]
Hi @fstab ,

thanks for taking time on this. 

I did reproduce my issue. Using a tomcat docker image as well as a jmx exporter image. Always using same configuration and same version of tomcat and/or exporter.

Check please this repo: [davidmpaz/reproduce-issue-666](https://github.com/davidmpaz/reproduce-issue-666), i am sorry for the name, i am not much of a superstitious or Iron Maiden fan, but the chance was simply too much around this issue number to let it pass :)

Do you see what i mean now with different metrics? Am i missing something here?

Regards,
David

**Comment by dhoard** [comment]
@davidmpaz I agree this looks like an issue.

If I run your `exporter-as-agent` branch code...

```
curl -s http://localhost:5566/ | grep OperatingSystem
```

... doesn't return any `OperatingSystem` metrics.

If I bash into the same running container and run `JmxScraper` directly...

```
cd /opt
java -cp ./jmx_prometheus_javaagent.jar io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper service:jmx:rmi:///jndi/rmi://tomcat:1099/jmxrmi
```
.... I get 15 `OperatingSystem` metrics.

```
java.lang{type=OperatingSystem}[]OpenFileDescriptorCount: 86
java.lang{type=OperatingSystem}[]MaxFileDescriptorCount: 1048576
java.lang{type=OperatingSystem}[]CommittedVirtualMemorySize: 12220633088
java.lang{type=OperatingSystem}[]TotalSwapSpaceSize: 2147479552
java.lang{type=OperatingSystem}[]FreeSwapSpaceSize: 2147479552
java.lang{type=OperatingSystem}[]FreePhysicalMemorySize: 10578288640
java.lang{type=OperatingSystem}[]TotalPhysicalMemorySize: 24745779200
java.lang{type=OperatingSystem}[]SystemCpuLoad: 0.1252103465853966
java.lang{type=OperatingSystem}[]ProcessCpuLoad: 9.208658331369185E-4
java.lang{type=OperatingSystem}[]ProcessCpuTime: 15370000000
java.lang{type=OperatingSystem}[]Version: 5.15.11-051511-generic
java.lang{type=OperatingSystem}[]AvailableProcessors: 8
java.lang{type=OperatingSystem}[]Arch: amd64
java.lang{type=OperatingSystem}[]SystemLoadAverage: 1.41
java.lang{type=OperatingSystem}[]Name: Linux
```

**Comment by dhoard** [comment]
After looking some more, running as an agent...

1. Only jvm metrics are returned

2. Tomcat logs have the following exception...

```
05-Jan-2022 16:57:17.461 SEVERE [prometheus-http-1-1] io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NoInitialContextException: Can
not instantiate class: org.apache.naming.java.javaURLContextFactory [Root exception is java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:240)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:161)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: org.apache.naming.java.javaURLContextFactory [Root exception is java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:674)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1953)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.apache.naming.java.javaURLContextFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:91)
	at com.sun.naming.internal.VersionHelper12.loadClass(VersionHelper12.java:61)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:672)
	... 24 more
```

**Comment by dhoard** [comment]
@davidmpaz This is a configuration issue.

When running as a java agent, you need to remove...

```
hostPort: "host:1099"
username:
password
```

Correct configuration...

```
---
rules:
  - pattern: ".*"
```

**Comment by fstab** [comment]
Thanks @dhoard for looking into it.

@davidmpaz does that solve this issue?

**Comment by davidmpaz** [comment]
Hi,

thank you very much @dhoard for your help here! Actually I realise i did not post the exception here, i though i did. Somewhere, maybe in google group, i did and forgot to mention it here also. So sorry for not fully describe it.

@fstab Indeed that solves the problem! Please let's add the PR I made in order to get the instructions easier for dummies?

Thanks again and cheers,
David
