### ISSUE TITLE
Problem with Tomcat 8.5 and datasource

### ISSUE THREAD

**Issue by yavi2k** [prometheus/jmx_exporter#714]
Hi,

I have one Tomcat 8.5 with jmx_exporter (jmx_prometheus_javaagent-0.16.1.jar) configured, normally works without problems but some times (6 o 7 times per day) jmx_exporter doesn't respond for some 20-30 minutes.

That is the response  when the jmx fail:
```
curl http://localhost:9101/metrics
curl: (56) Recv failure: Conexión reinicializada por la máquina remota
```

I've made a thread dump when the jmx is no responding, this is the state of the prometheus thread:
```
"prometheus-http-1-4" #130 daemon prio=5 os_prio=0 tid=0x00007f8ec421c000 nid=0x566b waiting for monitor entry [0x00007f8e9a797000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.toString(DelegatingConnection.java:92)
        - waiting to lock <0x000000069a116a48> (a org.apache.tomcat.dbcp.dbcp2.PoolableConnection)
        at org.apache.tomcat.dbcp.dbcp2.PoolableConnection.getToString(PoolableConnection.java:240)
        at sun.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
        at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
        at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
        at com.sun.jmx.mbeanserver.MBeanSupport.getAttributes(MBeanSupport.java:213)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:152)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:118)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:547)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:240)
        at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:161)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(TextFormat.java:202)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:57)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

All thread (five prometheus thread) are in BLOCKED state, after some minutes, jmx_exporter works again without make any changes.

This is my yaml file:
```
---
startDelaySeconds: 0
username: 
password: 
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames:
  - "Catalina:type=DataSource,*"
  - "Catalina:type=Manager,*"
rules:
  - pattern: 'Catalina<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions|activeSessions):'
    name: tomcat_session_$3_total
    labels:
      context: "$2"
      host: "$1"
    help: Tomcat session $3 total
    type: COUNTER
  - pattern: "Catalina<type=DataSource, host=(.*), context=(.*), class=(.*), name=\"(.*)\"><>(numActive|numIdle|maxTotal):"
    name: tomcat_jdbc_$5
    labels:
      context: "$2"
      class: "$3"
      name: "$4"
    help: Tomcat jdbc $4
    type: GAUGE
```
Maybe I have some bad configuration? 

Thanks

**Comment by dhoard** [comment]
Per the thread dump it looks like a deadlock in dbcp2 code.

**Comment by dhoard** [comment]
Closing due to inactivity.

**Comment by yavi2k** [comment]
Hi,

Sorry for not responding all this time.

We have tried with the last versión of jmx_exporter (1.1) but the problem persists.

We don't have any deadlock.

I attach the thread dump again (in this case with PostgreSQL). We have the same problem on different servers.
We think the problem is related to the measurement of the datasources status, because the stack dump indicates it.

"prometheus-http-1-1" #10 daemon prio=5 os_prio=0 tid=0x00007f400556f000 nid=0x18c74 waiting for monitor entry [0x00007f3fc1b19000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.postgresql.core.QueryExecutorBase.getStandardConformingStrings(QueryExecutorBase.java:269)
	- waiting to lock <0x000000069dc97200> (a org.postgresql.core.v3.QueryExecutorImpl)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:43)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:337)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:300)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at org.postgresql.jdbc.PgConnection.getSchema(PgConnection.java:1555)
	at org.apache.tomcat.dbcp.dbcp2.Jdbc41Bridge.getSchema(Jdbc41Bridge.java:366)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingConnection.getSchema(DelegatingConnection.java:960)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
	at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
	at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
	at com.sun.jmx.mbeanserver.MBeanSupport.getAttributes(MBeanSupport.java:213)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
	at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:236)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:181)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:781)
	at io.prometheus.metrics.model.registry.MultiCollector.collect(MultiCollector.java:21)
	at io.prometheus.metrics.model.registry.PrometheusRegistry.scrape(PrometheusRegistry.java:84)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.scrape(PrometheusScrapeHandler.java:135)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.handleRequest(PrometheusScrapeHandler.java:56)
	at io.prometheus.metrics.exporter.httpserver.MetricsHandler.handle(MetricsHandler.java:33)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

All the threads are in the same state.
