### ISSUE TITLE
java: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2

### ISSUE THREAD

**Issue by valeintinesowl** [prometheus/jmx_exporter#732]
Greetings! I'm trying to collect metrics with apache ignite, but I'm getting an error:
 `java: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2`. 
 Tried on two different hosts, one works, the other doesn't. What im doing wrong?

My queries file:

```---
startDelaySeconds: 0
#hostPort: 127.0.0.1:7020
jmxUrl: service:jmx:rmi:///jndi/rmi://{{ item.value.jmx_address }}:{{ item.value.jmx_port }}/jmxrmi
ssl: false
#lowercaseOutputLabelNames: false
lowercaseOutputName: true

rules:

#
# Default java metrics
#

- pattern: 'java.lang<type=(Memory)><([a-zA-Z\s]*)>(used|committed|max|init): (\d+)'
  name: jmx_java_lang_$1_$2_$3
  type: GAUGE
  value: $4

- pattern: 'java.lang<type=(Memory|Runtime|Threading)><([a-zA-Z\s]*)>([a-zA-Z\s])<>(used|committed|max|init): (\d+)'
  name: jmx_java_lang_$1_$2_$3
  type: GAUGE

- pattern: 'java.lang<type=(OperatingSystem)><>([a-zA-Z\s]*): (\d+)'
  name: jmx_java_lang_$1_$2
  type: GAUGE

- pattern: 'java.lang<type=(ClassLoading)><>(UnloadedClassCount|TotalLoadedClassCount|LoadedClassCount): (\d+)'
  name: jmx_java_lang_$1_$2
  type: COUNTER

- pattern: 'java.lang<type=(Compilation)><>(TotalCompilationTime|Name): (\d+)'
  name: jmx_java_lang_$1_$2
  type: GAUGE

- pattern: 'java.lang<type=(Runtime)><>(VmVersion|VmName|Uptime): (\d+)'
  name: jmx_java_lang_$1_$2
  type: GAUGE

- pattern: 'java.lang<type=(Threading)><>(TotalStartedThreadCount|ThreadCount|PeakThreadCount|DaemonThreadCount): (\d+)'
  name: jmx_java_lang_$1_$2
  type: GAUGE

- pattern: 'java.lang<type=(Memory)><>(ObjectPendingFinalizationCount): (\d+)'
  name: jmx_java_lang_$1_$2
  type: GAUGE

- pattern: 'java.lang<type=(GarbageCollector), name=([a-zA-Z\s0-9]*)><>(CollectionTime): (\d+)'
  name: jmx_java_lang_$1_$3
  labels:
    name: $2
  type: GAUGE

- pattern: 'java.lang<type=(GarbageCollector), name=([a-zA-Z\s0-9]*)><>(CollectionCount): (\d+)'
  name: jmx_java_lang_$1_$3
  labels:
    name: $2
  type: COUNTER

- pattern: 'java.lang<type=(MemoryPool), name=([a-zA-Z\s]*)><([a-zA-Z\s]*)>(committed|max|used): (\d+)'
  name: jmx_java_lang_$1_$3_$4
  labels:
    name: $2
  type: GAUGE

#
# Begin ignite metrics
#

# Ignite Cluster Info

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(IgniteCluster), name=(IgniteClusterMXBeanImpl)><>([a-zA-Z0-9\s]): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Data Region Size & Monitoring RAM Memory Usage

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(DataRegionMetrics), name=([a-zA-Z\s]*)><>(PagesFillFactor|TotalUsedPages|PhysicalMemoryPages|PhysicalMemorySize|PagesReplaceAge|TotalAllocatedSize|DirtyPages): (\d+)'
  name: jmx_org_apache_$1_$3
  labels:
    name: $2
  type: GAUGE

- pattern: 'org.apache<clsLdr=[a-zA-Z0  -9\s]*, group=(DataRegionMetrics), name=([a-zA-Z\s]*)><>(PagesWritten|PagesRead|PagesReplaced): (\d+)'
  name: jmx_org_apache_$1_$3
  labels:
    name: $2
  type: COUNTER

# Monitoring Storage Size

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=("Persistent Store"), name=(DataStorageMetrics)><>(TotalAllocatedSize|WalTotalSize|WalArchiveSegments): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Cache Group Size

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=("Cache groups"), name=([a-zA-Z\s]*)><>(TotalAllocatedSize): (\d+)'
  name: jmx_org_apache_$1_$3
  labels:
    name: $2
  type: GAUGE

# Monitoring Checkpointing Operations

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=("Persistent Store"), name=(DataStorageMetrics)><>(DirtyPages|LastCheckpointDuration|CheckpointBufferSize): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Monitoring Rebalancing

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=([a-zA-Z\s]*), name=(org.apache.ignite.internal.processors.cache.CacheLocalMetricsMXBeanImpl)><>(RebalancingStartTime|EstimatedRebalancingFinishTime|KeysToRebalanceLeft): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Monitoring Topology

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(Kernal), name=(ClusterMetricsMXBeanImpl)><>(TotalServerNodes|TotalClientNodes|TotalBaselineNodes|ActiveBaselineNodes): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(SPIs), name=(TcpDiscoverySpi)><>(Coordinator|CoordinatorNodeFormatted): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Monitoring Caches

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=([a-zA-Z\s]*), name=("org.apache.ignite.internal.processors.cache.CacheClusterMetricsMXBeanImpl")><>(CacheSize): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=([a-zA-Z\s]*), name=("org.apache.ignite.internal.processors.cache.CacheLocalMetricsMXBeanImpl")><>(CacheSize): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Monitoring Build and Rebuild Indexes

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=([a-zA-Z\s]*), name=(org.apache.ignite.internal.processors.cache.CacheLocalMetricsMXBeanImpl)><>(IndexRebuildInProgress): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

# Monitoring Transactions

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(TransactionMetrics), name=(TransactionMetricsMxBeanImpl)><>(LockedKeysNumber|TransactionsCommittedNumber|TransactionsRolledBackNumber|OwnerTransactionsNumber|TransactionsHoldingLockNumber): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: COUNTER

# Monitoring Message Queues - Communication Message Queue

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(SPIs), name=(TcpCommunicationSpi)><>(OutboundMessagesQueueSize): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE

- pattern: 'org.apache<clsLdr=[a-zA-Z0-9\s]*, group=(SPIs), name=(TcpDiscoverySpi)><>(MessageWorkerQueueSize|AvgMessageProcessingTime): (\d+)'
  name: jmx_org_apache_$1_$2_$3
  type: GAUGE
```

**Comment by valeintinesowl** [comment]
full trace:

```
Aug 30 12:34:23 host java: Aug 30, 2022 12:34:23 PM io.prometheus.jmx.JmxCollector collect
Aug 30 12:34:23 host java: SEVERE: JMX scrape failed: javax.management.RuntimeMBeanException: getMBeanInfo threw RuntimeException
Aug 30 12:34:23 host java: at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBeanInfo(DefaultMBeanServerInterceptor.java:1362)
Aug 30 12:34:23 host java: at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInfo(JmxMBeanServer.java:920)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1460)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.getMBeanInfo(RMIConnectionImpl.java:903)
Aug 30 12:34:23 host java: at java.base/jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
Aug 30 12:34:23 host java: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Aug 30 12:34:23 host java: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
Aug 30 12:34:23 host java: at java.base/java.security.AccessController.doPrivileged(Native Method)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
Aug 30 12:34:23 host java: at java.base/java.security.AccessController.doPrivileged(Native Method)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
Aug 30 12:34:23 host java: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Aug 30 12:34:23 host java: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Aug 30 12:34:23 host java: at java.base/java.lang.Thread.run(Thread.java:829)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
Aug 30 12:34:23 host java: at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.getMBeanInfo(Unknown Source)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getMBeanInfo(RMIConnector.java:1080)
Aug 30 12:34:23 host java: at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:131)
Aug 30 12:34:23 host java: at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:118)
Aug 30 12:34:23 host java: at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:599)
Aug 30 12:34:23 host java: at io.prometheus.client.Collector.collect(Collector.java:46)
Aug 30 12:34:23 host java: at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:197)
Aug 30 12:34:23 host java: at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:162)
Aug 30 12:34:23 host java: at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:183)
Aug 30 12:34:23 host java: at io.prometheus.client.CollectorRegistry.metricFamilySamples(CollectorRegistry.java:129)
Aug 30 12:34:23 host java: at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
Aug 30 12:34:23 host java: at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
Aug 30 12:34:23 host java: at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
Aug 30 12:34:23 host java: at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
Aug 30 12:34:23 host java: at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
Aug 30 12:34:23 host java: at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
Aug 30 12:34:23 host java: at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
Aug 30 12:34:23 host java: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Aug 30 12:34:23 host java: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Aug 30 12:34:23 host java: at java.base/java.lang.Thread.run(Thread.java:829)
Aug 30 12:34:23 host java: Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
Aug 30 12:34:23 host java: at java.base/java.lang.String.substring(String.java:1841)
Aug 30 12:34:23 host java: at org.apache.ignite.spi.metric.jmx.MetricRegistryMBean.lambda$getMBeanInfo$0(MetricRegistryMBean.java:105)
Aug 30 12:34:23 host java: at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
Aug 30 12:34:23 host java: at org.apache.ignite.spi.metric.jmx.MetricRegistryMBean.getMBeanInfo(MetricRegistryMBean.java:85)
Aug 30 12:34:23 host java: at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBeanInfo(DefaultMBeanServerInterceptor.java:1356)
Aug 30 12:34:23 host java: at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInfo(JmxMBeanServer.java:920)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1460)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
Aug 30 12:34:23 host java: at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.getMBeanInfo(RMIConnectionImpl.java:903)
Aug 30 12:34:23 host java: at java.base/jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
Aug 30 12:34:23 host java: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Aug 30 12:34:23 host java: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
Aug 30 12:34:23 host java: at java.base/java.security.AccessController.doPrivileged(Native Method)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
Aug 30 12:34:23 host java: at java.base/java.security.AccessController.doPrivileged(Native Method)
Aug 30 12:34:23 host java: at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
Aug 30 12:34:23 host java: ... 3 more
```

**Comment by fstab** [comment]
Hi, I just saw that you closed the issue. Did you solve it? I had it on my todo list, but didn't find the time last week.
