### ISSUE TITLE
jmx_exporter on Kafka Connect cannot provide details metric and will not continue to run

### ISSUE THREAD

**Issue by phionachao** [prometheus/jmx_exporter#811]
Hi All,

I have setup the jmx_exporter on the Kafka Connect server and encounter the below issue
1. running on httpserver but only provided jms Scrape metric
2. httpserver metric will be timeout after few mins

Don't know if there is any setting wrong the yaml, host = kafka connect URL

metrc provided below,

HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.18.0",name="jmx_prometheus_httpserver",} 1.0
HELP jmx_config_reload_success_total Number of times configuration have successfully been reloaded. TYPE jmx_config_reload_success_total counter
jmx_config_reload_success_total 0.0
HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded. TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
HELP jmx_scrape_duration_seconds Time this JMX scrape took, in seconds. TYPE jmx_scrape_duration_seconds gauge
jmx_scrape_duration_seconds 0.005625721
HELP jmx_scrape_error Non-zero if this scrape failed.
TYPE jmx_scrape_error gauge
jmx_scrape_error 1.0
HELP jmx_scrape_cached_beans Number of beans with their matching rule cached
TYPE jmx_scrape_cached_beans gauge
jmx_scrape_cached_beans 0.0
HELP jmx_config_reload_failure_created Number of times configuration have failed to be reloaded.
TYPE jmx_config_reload_failure_created gauge
jmx_config_reload_failure_created 1.686623800063E9
HELP jmx_config_reload_success_created Number of times configuration have successfully been reloaded.
TYPE jmx_config_reload_success_created gauge
jmx_config_reload_success_created 1.686623800061E9

exception of jmx_exporter

 io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:637)
        at io.prometheus.client.Collector.collect(Collector.java:45)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
        at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
        at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:218)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 19 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 24 more

Jun 13, 2023 10:36:41 AM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:637)
        at io.prometheus.client.Collector.collect(Collector.java:45)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
        at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
        at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:218)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 19 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 24 more

Jun 13, 2023 10:36:45 AM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:637)
        at io.prometheus.client.Collector.collect(Collector.java:45)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
        at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
        at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:218)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 19 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 24 more

Jun 13, 2023 10:36:45 AM io.prometheus.jmx.JmxCollector collect
SEVERE: JMX scrape failed: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:95)
        at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:637)
        at io.prometheus.client.Collector.collect(Collector.java:45)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71)
        at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53)
        at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:218)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 19 more
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 24 more

Thanks

Phi

**Comment by dhoard** [comment]
The best practice is to use the exporter in Java agent mode.

If you really need to use HTTP Server (standalone) mode, you have to configure the Kafka Connect JVM to expose JMX. Then use the application's JMX configuration information in your exporter YAML URL configuration.

Integration test example:

 https://github.com/prometheus/jmx_exporter/tree/main/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/Minimal_IT/Standalone

**Comment by phionachao** [comment]
Thanks for your information, i have tried to run javaagent but cannot get it thru the Yourjar.jar just wondering is there anything missing.

 $ java -javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml -jar:/opt/jvmexporter/yourJar.jar
bash: $: command not found...

**Comment by dhoard** [comment]
You add the javaagent argument to the command to run Kafka Connect.

Typically, Kafka Connect is ran via systemd.

The commandline you posted doesn't look correct.

**Comment by phionachao** [comment]
Hi 
so i have to add the java -javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml -jar /opt/jvmexporter/yourJar.jar to the Kafka Connect systemd for start up? Am i correct?

**Comment by dhoard** [comment]
Assuming you have...

1. created the directory `/opt/jvmexporter`
2. placed the export jar in the directory (i.e. `/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar`)
3. placed the configuration YAML in the directory (i.e. `/opt/jvmexporter/kafka-connect.yaml`)

Add the following JVM arguments...

 `-javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml`

... to your existing command line to run Kafka Connect.

If Kafka Connect is started/run using systemd, you will add the JVM arguments in the relevant systemd file.

**Comment by phionachao** [comment]
Thanks,

I have added below into the systemd file

Environment="KAFKA_OPTS=-javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml"
Environment="KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true"
Environment="KAFKA_HEAP_OPTS=-Xmx5120m -Xms5120m"

after restart the service seems it is not running, may i know if there is anything wrong?

Also do i require to add any arguement in connect-distribute.sh?

**Comment by dhoard** [comment]
You should add the arguments to `KAFKA_JMX_OPTS`

**Comment by phionachao** [comment]
Sorry I'm not quite familiar of this, should I add KAFKA_JMX_OPTS under connect-distribute.sh?

Since i have added below in systemd service file, this is not the argument you are referring?

Environment="KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true"

**Comment by dhoard** [comment]
You should append the values to your existing `KAFKA_JMX_OPTS` declaration.

```
Environment="KAFKA_JMX_OPTS=javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true"
```

**Comment by phionachao** [comment]
Hi, 

Since i didn't see the existing KAFKA_JMX_OPTS declaration so should I add KAFKA_JMX_OPTS under connect-distribute.sh?

**Comment by phionachao** [comment]
i have added  KAFKA_JMX_OPTS under connect-distribute.sh kafka connect running normal

but when i run below and try to monitor the kafka jar, it show no manifest error 


sudo java -javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml -jar /usr/share/java/kafka/kafka_2.12-5.4.0-ccs.jar
no main manifest attribute, in /usr/share/java/kafka/kafka_2.12-5.4.0-ccs.jar

**Comment by dhoard** [comment]
Per your previous post, you had `KAFKA_JMX_OPTS` in your systemd service file. You should add these as described in your systemd service file...

```
Environment="KAFKA_JMX_OPTS=javaagent:/opt/jvmexporter/jmx_prometheus_javaagent-0.18.0.jar=12345:/opt/jvmexporter/kafka-connect.yaml -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true"
```

**Comment by dhoard** [comment]
Closing due to inactivity.
