### ISSUE TITLE
Usage with Tomee-7.1 failed

### ISSUE THREAD

**Issue by zmichal-anasoft** [prometheus/jmx_exporter#820]
Hi,

 I'm trying to monitor TomEE-7.1 with default configuration provided from your web-site. But with this result:

```
SEVERE [prometheus-http-1-1] org.apache.openejb.monitoring.DynamicMBeanWrapper.getAttribute can't get properties value
       java.lang.reflect.InvocationTargetException
            at sun.reflect.GeneratedMethodAccessor402.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.openejb.monitoring.DynamicMBeanWrapper.getAttribute(DynamicMBeanWrapper.java:346)
            at org.apache.openejb.monitoring.DynamicMBeanWrapper.getAttributes(DynamicMBeanWrapper.java:380)
            at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttributes(DefaultMBeanServerInterceptor.java:709)
            at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttributes(JmxMBeanServer.java:705)
            at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:153)
            at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:118)
            at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:637)
            at io.prometheus.jmx.shaded.io.prometheus.client.Collector.collect(Collector.java:45)
            at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
            at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
  at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152                
       at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(TextFormat.java:202)
       at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:57
       at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
       at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
       at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
       at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
       at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
       at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
       at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748
    Caused by: java.lang.NullPointerException
       at org.apache.openejb.monitoring.LocalMBeanServer.tabularData(LocalMBeanServer.java:135)
       at org.apache.openejb.server.cxf.pojo.PojoWsContainer$WsServiceMBean.getProperties(PojoWsContainer.java:170)
                ... 26 more

```

**Comment by dhoard** [comment]
Per the stack trace, the issue appears to be in `org.apache.openejb.monitoring.DynamicMBeanWrapper`.

```
org.apache.openejb.monitoring.DynamicMBeanWrapper.getAttribute can't get properties value
```

**Comment by dhoard** [comment]
Closing due to inactivity.
