### ISSUE TITLE
Getting below error While enabling jmx-exporter in jboss-eap7.1

### ISSUE THREAD

**Issue by raagulrakesh** [prometheus/jmx_exporter#849]
I have used the jmx_prometheus_javaagent-0.19.0.jar

ERROR
[0m[31m08:42:37,694 ERROR [org.jboss.as.controller.management-operation] (prometheus-http-1-1) org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0268: Failed to rename temp file /home/jboss/jboss-eap-7.1/standalone/configuration/standalone.xml.tmp to /home/jboss/jboss-eap-7.1/standalone/configuration/standalone.xml: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0268: Failed to rename temp file /home/jboss/jboss-eap-7.1/standalone/configuration/standalone.xml.tmp to /home/jboss/jboss-eap-7.1/standalone/configuration/standalone.xml
	at org.jboss.as.controller.persistence.FilePersistenceUtils.moveTempFileToMain(FilePersistenceUtils.java:88)
	at org.jboss.as.controller.persistence.ConfigurationFile.commitTempFile(ConfigurationFile.java:570)
	at org.jboss.as.controller.persistence.ConfigurationFilePersistenceResource.doCommit(ConfigurationFilePersistenceResource.java:70)
	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
	at org.jboss.as.controller.ModelControllerImpl$3.commit(ModelControllerImpl.java:724)
	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:838)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:752)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:450)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1402)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:418)
	at org.jboss.as.controller.ModelControllerImpl.lambda$execute$0(ModelControllerImpl.java:227)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:263)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:229)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:227)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.execute(ModelControllerMBeanHelper.java:529)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:308)
	at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttributes(ModelControllerMBeanHelper.java:282)
	at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttributes(ModelControllerMBeanServerPlugin.java:146)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttributes(PluggableMBeanServerImpl.java:416)
	at io.prometheus.jmx.JmxScraper.scrapeBean(JmxScraper.java:153)
	at io.prometheus.jmx.JmxScraper.doScrape(JmxScraper.java:118)
	at io.prometheus.jmx.JmxCollector.collect(JmxCollector.java:642)
	at io.prometheus.jmx.shaded.io.prometheus.client.Collector.collect(Collector.java:45)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
	at io.prometheus.jmx.shaded.io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(TextFormat.java:202)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:57)
	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle(HTTPServer.java:100)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: /home/jboss/jboss-eap-7.1/standalone/configuration/standalone.xml: Device or resource busy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:447)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.jboss.as.controller.persistence.FilePersistenceUtils.moveTempFileToMain(FilePersistenceUtils.java:86)
	... 37 more

[0m

**Comment by dhoard** [comment]
Looks similar to your other issue https://github.com/prometheus/jmx_exporter/issues/848

Configuration of JBoss JMX access will need to be resolved via JBoss support/forums. This is out of scope from the exporter perspective.

**Comment by raagulrakesh** [comment]
ok, thanks.
Will check with JBoss support team
